### ISSUE TITLE
Add support for creating IoT Edge Deployments targeting multiple devices

### ISSUE THREAD

**Issue by jessebenson** [Microsoft/vscode-azure-iot-edge#104]
In Azure Portal, we can create an IoT Edge Deployment with a targetCondition to target multiple devices.  Add support for deploying a deployment.json (or a checked in deployment.edge.json?) that has the schema used for this Edge Deployment.

PUT /configurations/<id> (application/json body of the deployment manifest)

Looks like we need to do a GET /configurations/<id> and then either [1] DELETE+PUT or [2] PUT

**Comment by adashen** [comment]
@jessebenson it is in our backlog, but with low priority. Do you have any scenario for inner loop to deploy to multiple devices from vscode?
Another product we just delivered is the CI/CD  VSTS plugin https://marketplace.visualstudio.com/items?itemName=vsc-iot.iot-edge-build-deploy , which could be used in the CI/CD pipeline to deploy multiple devices.

**Comment by shizn** [comment]
a. deploy to multiple selected devices.
b. deploy to multiple devices with the same tag.

**Comment by LazarusX** [comment]
Creating Deployment for IoT Edge Device at Scale is supported now: https://github.com/Microsoft/vscode-azure-iot-toolkit/pull/112

**Comment by jessebenson** [comment]
Thank you!  This is perfect.
