### ISSUE TITLE
[Node] Build IoT Edge solution fail

### ISSUE THREAD

**Issue by xinyiz1226** [Microsoft/vscode-azure-iot-edge#119]
here is the message:

PS D:\EdgeBugbash1804\EdgeSolution> docker build  --rm -f "d:\EdgeBugbash1804\EdgeSolution\modules\FilterModule\Dockerfile" -t xinyizacr.azurecr.io/filtermodule:0.0.1-amd64 "d:\EdgeBugbash1804\EdgeSolution\modules\FilterModule" ; if ($?) { docker push xinyizacr.azurecr.io/filtermodule:0.0.1-amd64 }
Sending build context to Docker daemon  9.728kB
Step 1/8 : FROM node:8-slim
8-slim: Pulling from library/node
f2b6b4884fc8: Pulling fs layer
4fb899b4df21: Pulling fs layer
c669d5da499d: Pulling fs layer
03e8ff4c8721: Waiting
6c7c70b827c0: Waiting
8a798eae58ee: Waiting
context canceled

second try is successful

**Comment by LazarusX** [comment]
This should be an issue with Docker for Windows, as others have also reported (https://github.com/docker-library/docker/issues/71 and https://github.com/docker/for-win/issues/1240). Trying again or updating your Docker installation should fix it.
