### ISSUE TITLE
Add a user setting to enable auto save

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#127]
Kevin Saye:
when your right click on build package and build image, it should save or prompt to save any unsaved files.  I have had too many issues where I forgot to save and it rebuilt the wrong version.

**Comment by formulahendry** [comment]
Maybe user could leverage the 'Auto Save' feature of VS Code directly: https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save
