### ISSUE TITLE
Debug IoT Edge Custom Module with windows-amd64 Dockerfile failed

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#132]
Repro on 
Windows10
docker ：17.12.0-ce-win47
vscode latest insiders

step:
1.Build IoT Edge custom module with amd64 Dockerfile 
2.Replace the module's createOptions in deployment.json with below content and save this file: 
"createOptions": "{\"Env\":[\"DEBUG_OPTION=--inspect=0.0.0.0:9229\"],\"ExposedPorts\":{\"9229/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"9229/tcp\":[{\"HostPort\":\"9229\"}]}}}" 
Right click on an Edge device in device tree, select Create deployment for Edge device 
Create a launch.json file with below content: 
3.Run iotedgectl restart to restart Edge runtime 
After all the containers are running, navigate to debug view, and select “Debug IoT Edge Module filtermodule (Node.js)”, then press F5 
![image](https://user-images.githubusercontent.com/35018765/39394997-458a4122-4b0b-11e8-8e38-7e9e6a7b080b.png)

**Comment by LazarusX** [comment]
Close due to lack of activity. Please open a new one if you reproduce.
