### ISSUE TITLE
Set Docker build context

### ISSUE THREAD

**Issue by MaxiPigna** [Microsoft/vscode-azure-iot-edge#137]
I need to build a Docker image for a module starting from a .NET Core project referencing other projects.
Unfortunately, when I try to 'Build IoT Edge Module Image' by right clicking module.json, the build fails because the other projects are not within the Docker build context.
I saw that the build context is defined starting from the module.json location, so if I move the module.json upper in the folders tree it works, but I don't think this is the most elegant solution.

It would be nice the possibility to set a build context for each module. Or do you have a better solution to suggest?

**Comment by MPapst** [comment]
I am facing the same issue. When including a reference that is not provided by nuget, the docker image build fails.

The Scenario behind this is a shared library that provides serialization class for the json documents used as messages and a second library that provides an abstraction layer for the edge module handling.

**Comment by MaxiPigna** [comment]
I don't know if may help, but have you considered to configure .vscode/task.json file:
```
{
    "label": "build image",
    "command": "docker",
    "type": "shell",
    "args": [
        "build",
        "--rm",
        "-f",
        "'${workspaceFolder}\\modules\\mymodule\\Dockerfile.local.debug'",
        "-t",
        "127.0.0.1:5000/mymodule-module:latest-amd64.debug",
        "'${workspaceFolder}'"                                 <--- Set the right level here
    ],
    "problemMatcher": []
}
```

**Comment by adashen** [comment]
Fixed by https://github.com/Microsoft/vscode-azure-iot-edge/pull/227
you could now add a docker build context path in module.json. The context path is relative to the module.json file. Following is a sample
{
  "$schema-version": "0.0.1",
  "description": "",
  "image": {
    "contextPath": "../../"
    "repository": "localhost:5000/samplemodule3",
    "tag": {
      "version": "0.0.1",
      "platforms": {
        "amd64": "./Dockerfile.amd64",
        "amd64.debug": "./Dockerfile.amd64.debug",
        "arm32v7": "./Dockerfile.arm32v7",
        "arm32v7.debug": "./Dockerfile.arm32v7.debug",
        "windows-amd64": "./Dockerfile.windows-amd64",
        "windows-amd64.debug": "./Dockerfile.windows-amd64.debug"
      }
    },
    "buildOptions": []
  },
  "language": "CSharp"
}
