### ISSUE TITLE
Image placeholder and Dockerfile path verification error persists after renaming deployment.template.json/module.json 

### ISSUE THREAD

**Issue by LazarusX** [microsoft/vscode-azure-iot-edge#159]
Steps to reproduce
1. Open a valid deployment.template.json or module.json
2. Edit the image placeholder/Dockerfile path to make it invalid
3. Notice there is an error shown in VS Code's problem panel now.
4. Rename or delete deployment.template.json/module.json.
5. The error in Step 3 persists and you cannot make remove it unless you 1) rename the files back to deployment.template.json/module.json and correct the error, or 2) reload the window, or 3) restart VS Code.

**Comment by czgtest** [comment]
Fix work on v1.21.0-rc,  verification error will auto-remove after rename or delete deployment.template.json/module.json.
