### ISSUE TITLE
a module twin cannot be updated (but a device twin can).

### ISSUE THREAD

**Issue by lgongms** [Microsoft/vscode-azure-iot-edge#167]

**Comment by formulahendry** [comment]
Thanks @lgongms for you feedback! We are working on to enable updating Module Twin.

**Comment by formulahendry** [comment]
Hi @lgongms , this feature is implemented in [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) extension now. Please update to latest version and have a try.
![image](https://user-images.githubusercontent.com/1050213/41271813-24a55ba6-6e45-11e8-8010-80d1df331f48.png)
