### ISSUE TITLE
Docker/moby requires admin privileges on ubuntu

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#178]
it looks like the extension expects the current user to be able to run docker commands. turns out the default docker/moby installed requires admin privileges on ubuntu. either the extension should be able to sudo itself around (prompting for a password) or the error should be a little more helpful and our docs should reference a tutorial on how to enable that.
something like this: https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by jantielens** [comment]
I just bumped into this issue as well (while trying out the new VS Code Remote Development features). So I guess it will be much more common in the future to have this problem. The link you provided is indeed the correct solution IMHO. I've created a pull request to add both a FAQ and prerequisite related to this problem. #438
