### ISSUE TITLE
Permission denied issue when create an IoT Edge module project on Ubuntu

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#192]
https://review.docs.microsoft.com/zh-cn/azure/iot-edge/tutorial-csharp-module?branch=master
Repro on : ubuntu
Don't run visual-studio-code as root
step:
1.run the command Azure IoT Edge: New IoT Edge solution
2.Choose C# Module
3.Create an IoT Edge module project failed
![image](https://user-images.githubusercontent.com/35018765/42023246-f92ac470-7af1-11e8-99c1-8c5733a4c764.png)

**Comment by formulahendry** [comment]
In previous testing (did you use .net 2.0 on your Ubuntu?), did you meet with this issue?

**Comment by czgtest** [comment]
some files was created by root,  so it has permission issue when use normal user,  it is ubuntu enviroment issue,  now project can create successfully , so close it
