### ISSUE TITLE
need expose '5671' in deployment manifest

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#196]

**Comment by adashen** [comment]
fixed with PR https://github.com/Microsoft/vscode-azure-iot-edge/pull/211

**Comment by czgtest** [comment]
test pass on v1.2.0.-rc2

1.new iot edge solution
2.verify the deployment manifest

![image](https://user-images.githubusercontent.com/35018765/43630470-fd5f74f2-9732-11e8-81cb-fa0a55c53c8a.png)
