### ISSUE TITLE
[ASA] Get error when press ESC to cancel the selected ACA Job

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#210]
@SLdragon please make sure the fix is in master. After that please assign the issue to Chen Zhang for testing

**Comment by SLdragon** [comment]
@czgtest I have fixed the issue, and you can download the newest package here:

[azure-iot-edge-1.2.0-rc.zip](https://github.com/Microsoft/vscode-azure-iot-edge/files/2239838/azure-iot-edge-1.2.0-rc.zip)

**Comment by czgtest** [comment]
Now it work well ,  press ESC to cancel the select, can't get error now, verify pass for it. we can close it.

**Comment by SLdragon** [comment]
Thanks!
