### ISSUE TITLE
[ASA] ASA module  can't send message as expected

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#213]
steps:
	New IoT Edge solution (Create New IoT Edge solution using ASA module)  
	Add IoT Edge Module (Add ASA Module)  
	Build IoT Edge Solution  
	Deploy to Edge Device   

![image](https://user-images.githubusercontent.com/35018765/43434380-fb307fa0-94ad-11e8-96dd-6ea19ecdf4b7.png)

**Comment by SLdragon** [comment]
This issue is related edge runtime:

Here are some comments from edge runtime team:

> When this issue occurred, I didn’t find exception or error message in edgehub logs. Our customers also reported this problem before. I’d like to work with runtime team to investigate in the fix.

**Comment by SLdragon** [comment]
related issue:
https://github.com/Azure/iot-edge/issues/540

**Comment by adashen** [comment]
@czgtest  Please check whether the issue still reproduce. If not please close.

**Comment by czgtest** [comment]
this issue is not repro on, so close it now
