### ISSUE TITLE
improve error message when run IoT edge solution in simulator

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#222]
pre-step:

1.	Install iotedgehubdev tool: 
pip install --upgrade iotedgehubdev
2.	Install the pre-release bits of vscode-azure-iot-toolkit
https://iottoolkit.blob.core.windows.net/vscode/azure-iot-toolkit-1.2.0-rc.vsix
3.	Install the pre-release bits of vscode-azure-iot-edge
https://github.com/Microsoft/vscode-azure-iot-edge/releases/download/v1.2.0-rc2/azure-iot-edge-1.2.0-rc2.vsix

test step:
1. Azure IoT Edge: New IoT edge solution ---select Azure Stream Analytics --select Azure Stream Analytic jobs

2.Azure IoT Edge: build and run IoT edge solution in simulator.
it only display “error” message , The user simply doesn't know why this error occurred.
Actually this error is caused by not setup IoT edge simulator.
Can we tell user some firendly message instead of only an error  ? 
![image](https://user-images.githubusercontent.com/35018765/43770078-e51f6684-9a6d-11e8-8fb5-8e0a8f6fe8c2.png)

**Comment by czgtest** [comment]
OS and version used: Ubuntu 17.04

**Comment by adashen** [comment]
@czgtest plase check whether the issue exist now

**Comment by czgtest** [comment]
will auto-install  simulator tool on windows now.

it will reminder user to install simulator on ubuntu/mac now,
so close it
