### ISSUE TITLE
Sort module template quickpick items in alphabetical order

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode-azure-iot-edge#229]
From https://github.com/Microsoft/vscode-azure-iot-edge/pull/228#discussion_r211148639

**Comment by czgtest** [comment]
Now the module items display in order  Custom module -> Service Module -> Existing Module

![image](https://user-images.githubusercontent.com/35018765/45661407-01ee0300-bb30-11e8-9c88-940bb05e1a98.png)

**Comment by LazarusX** [comment]
Verified by @czgtest
