### ISSUE TITLE
[Java amd64.debug] debug Java Edge Module not work smoothly on vscode

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#236]
Repro on:
OS:windows10
java SDK:jdk-10.0.2
vscode : 1.26.1

pre-step:
1. install iotedgehubdev : pip install iotedgehubdev
2. install edge extension : 1.3.0-rc
3. install Java language support and debugger extensions
（Debugger for Java and Language Support for Java(TM) by Red Hat）

steps:
1. Azure IoT Edge: New IoT Edge Solution  --- select java module

2.Replace the module's createOptions in deployment.template.json: 
"createOptions":"{\"HostConfig\":{\"PortBindings\":{\"5005/tcp\":[{\"HostPort\":\"5005\"}]}}}" 
3.Replace the module's image tag in deployment.template.json:  
Replace ‘amd64’ with ‘amd64.debug’ 
5. Right click on an Edge device in device tree, and click Setup IoT edge simulator
6.Right-click the deployment.template.json file, and click Build and Run IoT Edge Solution in simulator

7.Add a breakpoint in MessageCallbackMqtt and EventCallback function 
8.After all the containers are running, navigate to debug view, and select “*** Remote Debug (Java)” 

9.Right click on an Edge device in device tree, and click start monitoring D2C message
10.Verify the breakpoint is only hit once.  and D2C message will not send messages cyclically

docker logs edgeHub
![image](https://user-images.githubusercontent.com/35018765/44442240-8158e700-a603-11e8-8fa0-4825b25f1c19.png)
docker logs SampleModuleJava
![image](https://user-images.githubusercontent.com/35018765/44442294-d137ae00-a603-11e8-8788-e606672a3253.png)

**Comment by adashen** [comment]
depends on https://github.com/Microsoft/vscode-java-debug/issues/374

**Comment by adashen** [comment]
@czgtest  The related issue is fixed please verify again.

**Comment by czgtest** [comment]
remote debug work well for java module now, so close it
