### ISSUE TITLE
[Java]give firendly message to tell user set up java environment instead of command failed 

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#237]
when user not set up java environment,  and create new java module solution in edge extension.

will pop up error message :  command failed with exit code 127

Can we give a friendly message for it ?

![image](https://user-images.githubusercontent.com/35018765/44509835-6bbbee00-a6e5-11e8-9567-dd1f56c71d7a.png)

**Comment by adashen** [comment]
@czgtest please verify the fix on 1.10 rc build

**Comment by czgtest** [comment]
@adashen here is latest error message, i don't think it is friendly
![image](https://user-images.githubusercontent.com/35018765/52777541-0424a100-307f-11e9-8e41-6e05a7e1aeac.png)

**Comment by czgtest** [comment]
on ubuntu,  the error message is not changing, still display "command failed with exit code 127"

**Comment by czgtest** [comment]
on Ubuntu，"Command failed with exit code 127. Detail: /bin/sh: 1: mvn: not found"  here is error message.
sync with Shen Wei, add "mvn: not found" to message box, currently this issue is temporarily fixed like this.
so I close it now.
