### ISSUE TITLE
[Java Module] local debug doesn't work

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#241]
OS, version, SKU and CPU architecture used: 
Windows 10, Version 18.06.1-ce-win73  linux container mode
Edge version used: 
1.3.0

Local debug error when start debugging

Start to create client with MQTT protocol 
com.microsoft.azure.sdk.iot.device.exceptions.ModuleClientException: Environment variable IOTEDGE_WORKLOADURI is required. 
at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:186) 
at com.edgemodule.App.main(App.java:72)

**Comment by adashen** [comment]
@czgtest  is this still a bug? seems env is not set correctly,  if not please close it

**Comment by czgtest** [comment]
For java module , local debug work well on liunx container, but not work on windows container,  because 8883 port is not found.
