### ISSUE TITLE
Unable to Module Direct Method

### ISSUE THREAD

**Issue by talmdal** [Microsoft/vscode-azure-iot-edge#242]
Using the pop command menu for a device in the "Azure IoT Hub Devices" panel one of the commands  available is "**Invoke Direct Method** which will invoke a direct method defined on the device.

However, if I expand the device to show the available modules and then right click on a running module, the only available command is "**Edit Module Twin**". There is no option to invoke a direct method on the module. The functionality is available on the Azure IoT hub portal

VS Code Version: 1.26.1
Azure IoT Edge Version: 1.3.0

**Comment by shizn** [comment]
Thanks for the feature request. We are still working on this. @formulahendry

**Comment by formulahendry** [comment]
Issue tracked in https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/110

**Comment by adashen** [comment]
new feature added in vscode toolkit for module direct method, @czgtest  please have a check

**Comment by czgtest** [comment]
Azure IoT Edge Version: 1.4.0

Right-click a module 
Click ‘Invoke Module Direct Method’ 
Input method name and  payload 
Verify we could get response 
![image](https://user-images.githubusercontent.com/35018765/45662174-61014700-bb33-11e8-8402-bbb5caeb7328.png)

![image](https://user-images.githubusercontent.com/35018765/45662272-be959380-bb33-11e8-9c21-02aac53c73f1.png)

**Comment by formulahendry** [comment]
Hi @talmdal , with v1.4.0 of [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit), Module Direct Method is supported.

**Comment by talmdal** [comment]
Thanks I saw that. I hadn't a chance to test it until now... thanks for a quick response
