### ISSUE TITLE
[windows-container]the time zone of docker is not match with system time

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#249]
OS: windows10
docker: windows container

1.create java module
2.build and run in simulator

 the system time is 2018-09-12 :11:00,  but the time of docker is 2018-09-13 01:48:19
so module will run failed.  

![image](https://user-images.githubusercontent.com/35018765/45473532-e79bda00-b769-11e8-8ce4-09d71bf77a8b.png)

**Comment by adashen** [comment]
We don't support java windows now, close the issue
