### ISSUE TITLE
command 'azure-iot-edge.newSolution' not found

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#258]
step:
1.disable  Azure IoT Toolkit in vscode extension

2.install edge extension

3. run "Azure IoT Edge : new IoT Edge Solution"

get error : command 'azure-iot-edge.newSolution' not found

The Toolkit  extension was disabled, causing the commands to fail. It seems like VS Code extensions enforce a dependency graph but do not enforce those dependencies be enabled.

**Comment by formulahendry** [comment]
This is the behavior of VS Code.
