### ISSUE TITLE
Why not add the route (sensorToSampleModuleNodejs) when adding new modules?

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#269]
step:
1.create new solution for c# function module
2.add IoT Edge module for Nodejs module
verify only add SampleModuleNodejsToIoTHub route,  why not automatically add sensorToSampleModuleNodejs ?
![image](https://user-images.githubusercontent.com/35018765/47403783-72b2bb80-d77d-11e8-85a1-edadadf7caf2.png)

3.build and push IoT Edge solution 

4.create development for Single device

5.verify logs for SampleModuleNodejs  
message is not sending.

**Comment by czgtest** [comment]
if automatically add sensorToSampleModuleNodejs when adding new modules
SampleModuleNodejs will receive message after deployment

**Comment by adashen** [comment]
When adding module, tempSensor module could have been deleted already.
