### ISSUE TITLE
context Path is not right on ubuntu

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#271]
"contextPath": ".\\"

iot@iot-box:~/Documents/file/1009/EdgeSolutionjava/EdgeSolution25$ docker build  --rm -f "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/Dockerfile.amd64" -t localhost:5000/samplemodule25:0.0.1-amd64 "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/.\"

"contextPath": ".\\abc"
iot@iot-box:~/Documents/file/1009/EdgeSolutionjava/EdgeSolution25$ docker build  --rm -f "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/Dockerfile.amd64" -t localhost:5000/samplemodule25:0.0.1-amd64 "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/.\"

"contextPath": "\\home\\iot\\Document\\file\\1009\\"

iot@iot-box:~/Documents/file/1009/EdgeSolutionjava/EdgeSolution25$ docker build  --rm -f "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/Dockerfile.amd64" -t localhost:5000/samplemodule25:0.0.1-amd64 "/home/iot/Documents/file/1009/EdgeSolutionjava/EdgeSolution25/modules/SampleModule25/\home\iot\Document\file\1009\"

**Comment by formulahendry** [comment]
back slash is invalid on Linux
