### ISSUE TITLE
CreateOption parse error when there is line break in the createoption string

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#278]
Detail could be found at 
https://github.com/Microsoft/vscode-azure-iot-edge/pull/275

**Comment by czgtest** [comment]
@adashen  I create new solution for nodejs module  and replace createOptions value as bellow.
1. build and push  IoT edge solution successfully.

2. run in simulator failed

"createOptions": "{\r\n  \"ExposedPorts\": {\r\n    \"1680/udp\": {}\r\n  },\r\n  \"HostConfig\": {\r\n    \"PortBindings\": {\r\n      \"1680/udp\": [\r\n        {\r\n          \"HostPort\": \"1680\",\r\n          \"HostIp\":\"172.17.0.1\"\r\n        }\r\n      ]\r\n    }\r\n  }\r\n}\r\n\r\n"

![image](https://user-images.githubusercontent.com/35018765/48750736-aa991a00-ecbb-11e8-9468-91dae54da410.png)

**Comment by czgtest** [comment]
this fix work well on both edge runtime and simulator,  so close it.
