### ISSUE TITLE
Run solution command needs to match files with platform 'windows-amd64'

### ISSUE THREAD

**Issue by michaeljqzq** [Microsoft/vscode-azure-iot-edge#281]
package.json => Line 96
```
{
          "when": "resourceFilename =~ /deployment(?!\\.template\\.)(\\.[a-z0-9]+)*(\\.debug)?.json/",
          "command": "azure-iot-edge.runSolution",
          "group": "edge@0"
},
```

the regexp needs to include '-' in platform name

**Comment by michaeljqzq** [comment]
@adashen

**Comment by czgtest** [comment]
test on azure-iot-toolkit-1.7.0-rc.vsix and azure-iot-edge-1.6.0-rc2.vsix.

1.create new solution for nodejs module
2.select default platform to windows-amd64
3.right-click deployment.template.json and generate deployment manifest 

4.right-click deployment.windows-amd64.json 
verify "run Iot Edge solution in  simulator " menu is display.

![image](https://user-images.githubusercontent.com/35018765/48757390-82b7af80-ecd7-11e8-839b-ab8b2ff0a691.png)
