### ISSUE TITLE
[Import third-party template] The module’s image  and createOptions is empty for third-party template

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#291]
this issue repro on azure-iot-edge-1.6.0-rc.vsix

1.create new solution for "C# TypeEdge Module" 
2.click deployment.template.json and select "add IoT edge module"
3.add  "My Node Module"
Verify the deployment.template.json and deployment.debug.template.json file is updated: A new module JSON is added into the modules section.
but the image /createOptions is empty for module in deployment.debug.template.json

![image](https://user-images.githubusercontent.com/35018765/48689085-e2dd2180-ec03-11e8-8308-278ce35bfee0.png)

**Comment by formulahendry** [comment]
@czgtest Please test with https://github.com/Microsoft/vscode-azure-iot-edge/releases/download/v1.6.0-rc2/azure-iot-edge-1.6.0-rc2.vsix

**Comment by czgtest** [comment]
@formulahendry  The module’s image is right now, but for "My Node Module",  The module’s createOptions should not be empty .  
![image](https://user-images.githubusercontent.com/35018765/48749075-36a74380-ecb4-11e8-8f57-40e84d7b8d2c.png)
if we add node module,  The module’s createOptions should be like this.
![image](https://user-images.githubusercontent.com/35018765/48749070-2f803580-ecb4-11e8-8755-d6f0d49eaa7d.png)

**Comment by formulahendry** [comment]
createOptions is empty. It is as design
