### ISSUE TITLE
[Multi platform support] Create deployment for Edge device is not support now

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#294]
this issue repro on azure-iot-edge-1.6.0-rc.vsix

1.Finished  ‘Build IoT Edge Solution’ 
2.Right click on deployment.amd64.json file, select Create deployment for Edge device 
In device dropdown list, select a device to deploy 

 “Create deployment for Edge device” command is not display now  in deployment.debug.amd64.json and deployment.amd64.json

**Comment by adashen** [comment]
@formulahendry please help to support the context on these files

**Comment by formulahendry** [comment]
@czgtest Please test with https://github.com/Microsoft/vscode-azure-iot-edge/releases/download/v1.6.0-rc2/azure-iot-edge-1.6.0-rc2.vsix

**Comment by formulahendry** [comment]
@czgtest Please test with latest IoT Toolkit: https://github.com/Microsoft/vscode-azure-iot-toolkit/releases/download/v1.7.0-rc/azure-iot-toolkit-1.7.0-rc.vsix

**Comment by czgtest** [comment]
fix work on latest toolkit , so close it
