### ISSUE TITLE
[Multi platform support]the platform button will not display on status bar and user can't select it again

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#295]
this issue repro on azure-iot-edge-1.6.0-rc.vsix

![image](https://user-images.githubusercontent.com/35018765/48700523-2301cb80-ec27-11e8-8fbf-e1fb8c5d0d3f.png)

after do the step1-6.

click deployment.template.json  again in vscode
verify the platform button will never display on status bar and user can't select it again

**Comment by adashen** [comment]
Close as cannot reproduce
