### ISSUE TITLE
[Import third-party template] no launch.json in .vscode folder,  is it expect?

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#296]
this issue repro on azure-iot-edge-1.6.0-rc2.vsix

1.create new solution for "C# TypeEdge Module"
2.click deployment.template.json and select "add IoT edge module"
3.add "My Node Module"
Verify there is no  launch.json in .vscode folder.   is it expect?

![image](https://user-images.githubusercontent.com/35018765/48749164-97cf1700-ecb4-11e8-8493-48dc37aa9c8a.png)

**Comment by formulahendry** [comment]
Yes, it is by design
