### ISSUE TITLE
[Multi target platform support] The module’s image and createOptions is empty for an existing module by importing from ACR

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#299]
this issue repro on azure-iot-edge-1.6.0-rc.vsix
1.create new solution for an existing module by importing from ACR
2. select "czgacr.azurecr.io" and "samplemodulenewpython"  , then "0.0.1-amd64.debug"
3.Verify the deployment.template.json and deployment.debug.template.json file is updated: A new module JSON is added into the modules section.

but The module’s image and createOptions is empty in deployment.debug.template.json

**Comment by czgtest** [comment]
The module’s image and createOptions is empty too for Stream Analytics Module,

**Comment by adashen** [comment]
duplicate with https://github.com/Microsoft/vscode-azure-iot-edge/issues/298

**Comment by czgtest** [comment]
fix work on azure-iot-edge-1.6.0-rc3.vsix ，test pass for ACR/ASA module
![image](https://user-images.githubusercontent.com/35018765/48816055-a8969000-ed7b-11e8-8de0-4ddbd074fd61.png)
