### ISSUE TITLE
[Multi target platform support]the default platform is not saving after create new solution

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#300]
repro on  azure-iot-edge-1.6.0-rc2.vsix * windows-container

1.  create new solution for nodejs module
2.  select v-czg@microsoft.com(windows-amd64) as default platform
 "azure-iot-edge.platforms": { 
        "amd64": ["v-czg@microsoft.com"], 
        "arm32v7": [], 
        "windows-amd64": ["v-czg@microsoft.com"] 
    },
3.verify workspace settings
![image](https://user-images.githubusercontent.com/35018765/48806684-1af47980-ed56-11e8-9172-2d8dcb427bcf.png)

4.  create another new solution for nodejs module again
5. verify the default platform in status bar 
expected:  v-czg@microsoft.com(windows-amd64) 
Actually: amd64
![image](https://user-images.githubusercontent.com/35018765/48806761-50996280-ed56-11e8-9b81-95b9a0c86edf.png)
sometime this error will repro on.
![image](https://user-images.githubusercontent.com/35018765/48806610-d4068400-ed55-11e8-83a9-ec3719f370cd.png)

**Comment by adashen** [comment]
This is as designed. The default platform is bond to workspace. If you would like to keep it on the machine. You could manually put the configuration into "USER SETTINGS" instead of "WORKSPACE SETTINGS".
@czgtest please make sure if you put in user settings the configuration could remain

**Comment by czgtest** [comment]
yes, the user setting configuration can remain after create new solution
