### ISSUE TITLE
Support deeper folder structure for `modules` folder

### ISSUE THREAD

**Issue by Scythen** [Microsoft/vscode-azure-iot-edge#303]
In order to manage module projects as interchangeable components a more complex folder structure would be beneficial. Each module should be able to have its own test and library projects. Additionally, each module should support CI/CD. In order to support this, the modules folder should support a structure similar to the following:
```
/modules
    /FirstModule
        /module
        /tests
        /library
    /SecondModule
        /module
        /tests
        /library
````
This structure would allow each module to be stored in its own git repo with its own CI/CD.
Solutions could be kept locally as a tool for developers to work with a combination of modules or if the solution is also stored in git,  modules could be mapped into a solution using git submodules.

**Comment by adashen** [comment]
@Scythen , Actually, you just need to put module.json under "FirstModule", "SecondeModule", and the tooling should work.

**Comment by adashen** [comment]
Since there is no further comment. Close the issue for now. Please feel free to open if you have any other issues.

**Comment by corollaries** [comment]
@adashen Asking it here since we have the same problem. 
In our project we're using various languages for the IoT Edge modules (such as NodeJS, C# and CPP).
Ideally we would like to have a structure like this:
```
/modules
    /js
        /module1
            /module.json
        /module2
            /module.json
    /cpp
        /module1
            /module.json
        /module2
            /module.json
```
However, this breaks for example the `Build IoT Edge Solution` functionality.
Is there any way we can make a directory structure like this work?

**Comment by xinyiz1226** [comment]
@corollaries we will support relative path in deployment.template.json soon, which should work in your scenario. Will let you know when it is available. Thank you.
