### ISSUE TITLE
[Config the version settings] create new solution error when set the version configuration to "null"

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#312]
Repro on 1.7.0-rc

 // Set the C module template version, which will be refernced during scaffolding C module. null for latest. (value set: is the branch /tag name) 
  "azure-iot-edge.version.cmodule": null,

there is a incorrect type, expected string.
![image](https://user-images.githubusercontent.com/35018765/49484717-ff6b9180-f872-11e8-924f-d8d0388fe5b2.png)

if change this value to string. 
 "azure-iot-edge.version.cmodule": "null",

then create new solution failed
![image](https://user-images.githubusercontent.com/35018765/49484697-eb279480-f872-11e8-80ec-52ef6c455c39.png)

**Comment by adashen** [comment]
because you set an invalid config, of cause will fail
