### ISSUE TITLE
[Config the version settings] the nodejs module is not latest when set version to null

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#313]
Repro on 1.7.0-rc

1. Set the Nodejs module template version to null or "1.3.0"
"azure-iot-edge.version.nodemodule": null,

2. create new solution for Nodejs module

3. verify the nodejs module code is not latest .
the Nodejs module code is coming from 
"npm i -g https://github.com/Azure/generator-azure-iot-edge-module/archive/v1.3.0-rc.tar.gz"
so Nodejs module is not support version configuration in user settings.

**Comment by adashen** [comment]
node config is removed close as fixed
