### ISSUE TITLE
the module and image is dulplate for  existing module (enter full image url)

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#325]
create new solution for existing module (enter full image url)

input module name and provide docker image : localhost:5000/samplemodulejava:0.0.1-amd64

the project is created 

verify there are the same module and image both in the deployment.template.json  and deployment.debug.template.json

![image](https://user-images.githubusercontent.com/35018765/50061914-ec47b280-01de-11e9-8009-77978512ddcf.png)

right-click deployment.template.json  --- add iot edge module---existing module (enter full image url)

input module name and provide docker image : localhost:5000/samplemodulejava:0.0.1-amd64.debug

verify it has the same image and module again in deployment.template.json  and deployment.debug.template.json

can we automatically recognize image and add it in template.json?

![image](https://user-images.githubusercontent.com/35018765/50061984-49dbff00-01df-11e9-9442-c5d523ea7fcb.png)

**Comment by adashen** [comment]
What is the expected behavior? It seems all things works as expected @czgtest
