### ISSUE TITLE
Expose solution path in deployment template

### ISSUE THREAD

**Issue by arabold** [Microsoft/vscode-azure-iot-edge#327]
I'm setting up live *Node.js* code reload and are mounting my local source folder in my docker modules like this:

**deployment.debug.template.json**
```json
          "SampleModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.SampleModule}.debug",
              "createOptions": {
                "HostConfig": {
                  "Mounts": [
                    {
                      "Target": "/app",
                      "Source": "/full/path/to/MyIotEdgeSolution/modules/SampleModule",
                      "Type": "bind"
                    }
                  ]
                }
              }
            }
          },
```

This works actually really well, but has the drawback that I need to hardcode an absolute path in the `Source` property. Using a relative path (i.e. `./modules/SampleModule`) won't work either, as that points to `/var/lib/iotedgehubdev/` instead.

I was hoping there's a variable placeholder that would point to the solution directory which I could use instead. I.e. replace
```
"Source": "/full/path/to/MyIotEdgeSolution/modules/SampleModule",
```
with
```
"Source": "${SOLUTION_DIR}/modules/SampleModule",
```

Any suggestions or ideas?

**Comment by adashen** [comment]
Hi @arabold Thanks for the suggestion. One work around is you could set ${SOLUTION_DIR} as your environment variable, so when generating the final deployment.json it will be expanded. This may not solve your problem totally, but could help in certain extent.

**Comment by adashen** [comment]
The workaround should solve user's issue. Close it now. Please feel free to open if there is any issue.
