### ISSUE TITLE
Bootstrapping a new solution with a module image in MCR

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-azure-iot-edge#342]
From Sebastian Bader[MSFT]

When I create a new Edge solution from scratch using the VS Code plugin, I noticed a few issues:
 
I’m creating a module from an existing module that is hosted on MCR (mcr.microsoft.com/iotedge/opc-publisher:2.2.0-linux-amd64). This caused the deployment to create an entry in the credentials section, which is of course not required:
![image](https://user-images.githubusercontent.com/3619378/50851966-1a7a6700-1333-11e9-953b-97c39260626f.png)

 
Why is the simulated temp sensor always added to the deployment – in addition to the module that I imported from a container registry?

There is a route created from the tempSensor into an – non-existing – input of my imported module.
"sensorToopcpublisher": "FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO BrokeredEndpoint(\"/modules/opcpublisher/inputs/input1\")"

Why would we assume that any module that the user creates, takes that as an input? If it is merely to give an example of a brokered route, IMHO we should provide that somehow differently.
 
Overall this leads to a deployment file which is not really usable without manual editing.

**Comment by adashen** [comment]
@czgtest , please the issue with latest release candidate package.

**Comment by czgtest** [comment]
Hi Shen Wei,
If it is mcr.microsoft.com or localhost, registryCredentials is expected not to append.
for example:
mcr.microsoft.com/azure-functions/base
mcr.microsoft.com/iotedge/opc-publisher:2.2.0-linux-amd64
localhost:5000/samplemodulecsharp

If it is acr or other case, registryCredentials is expected to append.
for example:
microsoft/mssql-server-linux:2017-latest
marketplace.azurecr.io/crosser/crosser/edgenode:latest

if it is invalid image , registryCredentials is expected to append too
testcase/samplemodule06:0.0.1-amd64

**Comment by czgtest** [comment]
this issue fix work, other scenarios will fix on #400
