### ISSUE TITLE
IoT Edge VS Code project compatible with VS project

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#345]
In a dev team, one scenarios is - some of the dev prefer VS and others prefer VS Code. We probably need a doc, some scripts, or tooling support for this scenario.

**Comment by shizn** [comment]
https://github.com/MicrosoftDocs/azure-docs/issues/21774

**Comment by adashen** [comment]
Now user could open VS created edge project in VSCode. So close it here.
