### ISSUE TITLE
launch.json is not generated for debug (new)

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#354]
now launch.json is not generated for debug (new)
![image](https://user-images.githubusercontent.com/35018765/51825580-087f5900-2320-11e9-8835-95e53e231aa3.png)

**Comment by adashen** [comment]
https://github.com/Microsoft/vscode/issues/68129
https://github.com/Microsoft/vscode/issues/37648

**Comment by adashen** [comment]
@czgtest Please verify the fix on the latest release candidate

**Comment by czgtest** [comment]
fix work,  launch json can be generate on edge v1.11.0-rc, so close it
