### ISSUE TITLE
create deployment for single module not work after Use azure-iot-edge.executor.env to set “DOCKER_HOST”

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#355]
Use azure-iot-edge.executor.env to set “DOCKER_HOST”   ：  Pass
![image](https://user-images.githubusercontent.com/35018765/51828418-88102680-2326-11e9-9ad1-3729f79d5954.png)
then iotedgehubdev stop in vscode

 docker -H "npipe:////./pipe/iotedge_moby_engine" system prune -f -a
 docker -H "npipe:////./pipe/iotedge_moby_engine" image list
make sure there is no image item
remove settings and reload vscode
"azure-iot-edge.executor.env": {
        "TEST_ENV":"hello",
        "DOCKER_HOST": "npipe:////./pipe/iotedge_moby_engine"
    }

create new solution for python module
build and push module for amd64 docker file
create deployment for single module 
verify python module is not work in docker ce

**Comment by adashen** [comment]
since the env is windows container, which does not support python close
