### ISSUE TITLE
Remove hard requirement on modules folder

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode-azure-iot-edge#357]
Steps to reproduce:
1. Create a new solution
2. Remove all modules in template.json files except the tempSensor module
3. Remove the `modules` folder
4. Run "Generate IoT Edge deployment manifest" command and see the error

Even if the user manually creates an empty `modules` folder, git will ignore it so another user who pulls down the repo will need to manually create the `modules` folder again.

**Comment by adashen** [comment]
@czgtest please check this fix with 1.10 rc build. Remove the modules folder from an edge solution. And make sure an edge solution with just deployment.template.json (which has some environment variables) could also work.

**Comment by czgtest** [comment]
Test on edge 1.9.0
Run "Generate IoT Edge deployment manifest" command and see the error
![image](https://user-images.githubusercontent.com/35018765/52772979-d5a1c880-3074-11e9-9e56-65b6707eb6ed.png)

Test on edge 1.10.0-rc
create new solution with localhost 
Run "Generate IoT Edge deployment manifest" command 
generate the deployment.amd64.json successfully

create new solution with ACR
Run "Generate IoT Edge deployment manifest" command 
generate the deployment.amd64.json successfully

![image](https://user-images.githubusercontent.com/35018765/52774277-cf611b80-3077-11e9-8b65-f155f45e7173.png)
