### ISSUE TITLE
CookieCutter installs in my roaming profile and then tells me to add it the path, even tho Python is already installed

### ISSUE THREAD

**Issue by drwill-ms** [Microsoft/vscode-azure-iot-edge#359]
- VSCode Version: 1.31.0
- OS Version: Windows 10
- Extension Version: 1.7.0

**Steps**
Have a Windows VM with Python installed (choco install python if you use chocolatey)
Install cookiecutter to set up a python module for edge by running: pip install --upgrade --user cookiecutter.

**Actual**
Execution ends with this warning: " The script cookiecutter.exe is installed in 'C:\Users\markmyd\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location."

**Expected**
Either use my existing python path to scripts (c:\python37\scripts) or add this location to my path

Does this issue occur when all other extensions are disabled?: Yes

**Comment by drwill-ms** [comment]
#AzureIoTE2E

**Comment by adashen** [comment]
@drwill-ms , now python scaffolding doesn't need cookiecutter any more. Can you try extension with latest version?

**Comment by drwill-ms** [comment]
@adashen confirmed, this works without installing it. Thanks!

**Comment by adashen** [comment]
Close as the fix has been verified. Please feel free to open if there is any other issue.
