### ISSUE TITLE
Each new IoT Edge solution comes with the “tempSensor” demo module by default and one has to manually remove it

### ISSUE THREAD

**Issue by drwill-ms** [microsoft/vscode-azure-iot-edge#360]
- VSCode Version: 1.31.0
- OS Version: 10
- Extension Version: 1.7.0

Steps to Reproduce:

1. New IoT Edge solution
2. Note tempSensor demo module
3. Remove tempSensor demo module

Expected
A template solution should come with what I need, and not demo stuff. When I'm trying to do real work after having learned IoT modules, this becomes annoying and distracting.

Does this issue occur when all other extensions are disabled?: Yes

**Comment by drwill-ms** [comment]
#AzureIoTE2E

**Comment by adashen** [comment]
@drwill-ms Thanks for the suggestion. We will add this to our backlog and to see how to help both new users and advanced users.

**Comment by adashen** [comment]
Now "tempSensor" is not added automatically when adding module from marketplace and we have option to create empty solution. So close the issue.
