### ISSUE TITLE
Monitor of device to cloud data seems broken

### ISSUE THREAD

**Issue by drwill-ms** [Microsoft/vscode-azure-iot-edge#361]
- VSCode Version: 1.31.0
- OS Version: 10
- Extension Version: 1.7

Steps to Reproduce:

1. Generate a bunch of devices and device data
1. Right click on a device for which data is being sent and start device to cloud monitoring
1. I never get any device data as I would expect

![image](https://user-images.githubusercontent.com/14119884/52591241-4c7e5d80-2df8-11e9-8120-9cca6f11d1d1.png)
![image](https://user-images.githubusercontent.com/14119884/52591252-5011e480-2df8-11e9-9d27-a5ec97f16e5d.png)

Does this issue occur when all other extensions are disabled?: Yes

**Comment by drwill-ms** [comment]
#AzureIoTE2E

**Comment by formulahendry** [comment]
@drwill-ms , did you set up route similar to https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/180 ?
And , could you use Azure IoT Hub Toolkit to send a D2C message to see if the message is captured in output?

**Comment by drwill-ms** [comment]
The only route I have set up is to write AVRO files to blob storage. If I browse storage, I can see files with my D2C messages. VSCode just didn't seem to intercept it.

Note that the C2D monitoring worked fine. I used the IoT Hub devices page to send a message, and VSCode showed that message.

We're using the SDK to send events:
```
            using (Message eventMessage = new Message(Encoding.UTF8.GetBytes(message)))
            {
                // Set the content type and encoding so the IoT Hub knows to treat the message body as JSON
                eventMessage.ContentEncoding = "utf-8";
                eventMessage.ContentType = "application/json";

                await deviceClient.SendEventAsync(eventMessage).ConfigureAwait(false);
            }
```

But I've also used the VSCode option to send a D2C message and it doesn't capture it either.

**Comment by formulahendry** [comment]
> The only route I have set up is to write AVRO files to blob storage.

Hi @drwill-ms , that should be the reason which is the same as https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/180 .
Once a Route is created, data stops flowing to the built-in-endpoint unless a Route is created to that endpoint. 
If you want to read all messages arrived in IoT Hub no matter where the message will be routed, just add the built-in-endpoint to routes, then you will be able to monitor the data using this extension.

Feel free to reopen or create a new issue if you need any other help.

**Comment by formulahendry** [comment]
Hi @drwill-ms, now we have a [FAQ page](https://github.com/Microsoft/vscode-azure-iot-toolkit/wiki/FAQ) in Wiki of Azure IoT Hub Toolkit, which mention the ways to read device-to-cloud messages from the built-in and custom endpoints. Besides, we also published a [blog post ](https://devblogs.microsoft.com/iotdev/read-azure-iot-hub-device-to-cloud-messages-from-the-built-in-and-custom-endpoints/)about this.

Let us know if you need any other help on this. 😄
