### ISSUE TITLE
Set Default Platform: Error: Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again.

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#364]
- VSCode Version: 1.30.1
- OS Version:
- Extension Version: 1.9.0

Steps to Reproduce:

1. Close workspace in vscode.
2. Use command palette to call "Set Default Target Platform for Edge Solution"
3. Error message will show "Unable to write to Workspace Settings because no workspace is opened. Please open a workspace first and try again."

**Comment by adashen** [comment]
@czgtest Please verify the bug when testing 1.10 rc. Now the error message is clear and will now let user start to select platform

**Comment by czgtest** [comment]
verify pass on 1.10 rc,  the error message will pop up as bellow.
No workspace is opened for setting default platform. Please open a workspace and try again.

![image](https://user-images.githubusercontent.com/35018765/52770272-9a4fcb80-306d-11e9-9d58-fcace1fd04f1.png)
