### ISSUE TITLE
[gallery page] the latest version is 1.9.0

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#367]
- VSCode Version:1.31.1
- OS Version: windows
- Extension Version:1.10.1rc

Steps to Reproduce:

1.open gallery page
2.verify the version is 1.8.0, but latest version is 1.9.0 and publish date should be updated too
![image](https://user-images.githubusercontent.com/35018765/52762031-c6108880-3050-11e9-8584-90b90ee18373.png)

**Comment by SLdragon** [comment]
OK, thanks, the version infomation can be updated by this repo:
https://github.com/Azure-Samples/vscode-azure-iot-edge-sample-gallery

And I will update this part when our edge extension is released.

**Comment by adashen** [comment]
Keep this open until the aside info is moved into extension instead of putting in the gallery repo.

**Comment by SLdragon** [comment]
https://github.com/Microsoft/vscode-azure-iot-edge/pull/376
