### ISSUE TITLE
Set Module Credentials to User Settings command failed with exit code 1. Detail:

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#368]
- VSCode Version: 1.31.1
- OS Version: windows 
- Extension Version: 1.10-rc1

Steps to Reproduce:

1.Close workspace in vscode.
2. Use command palette to call "Azure IoT Edge: Set Module Credentials to User Settings"
3. Error message will show "Command failed with exit code 1. Detail:"
Expect message :  Please run 'setup iot edge simulator' first and try again.

![image](https://user-images.githubusercontent.com/35018765/52771890-19470300-3072-11e9-9468-400b0c9c5fe9.png)

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by czgtest** [comment]
Azure IoT Edge: Start IoT Edge Hub Simulator for Single Module has the same issue

**Comment by LazarusX** [comment]
Thanks for the suggestion!

https://github.com/Azure/iotedgehubdev/pull/171 will fix this. Preview:

![image](https://user-images.githubusercontent.com/716650/52774274-cec88500-3077-11e9-9d79-1bb7956f6aa3.png)

**Comment by adashen** [comment]
@czgtest please check on latest release

**Comment by czgtest** [comment]
if user not set up device connection string , then run "Azure IoT Edge: Set Module Credentials to User Settings",  here is windows message
![image](https://user-images.githubusercontent.com/35018765/63907952-f3061500-ca4f-11e9-8b8f-1b7ddcca1687.png)
