### ISSUE TITLE
[Custom Vision sample] improve performance for amr32v7 template

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#370]
- VSCode Version: 1.31.1
- OS Version: windows
- Extension Version:1.10.0-rc

Steps to Reproduce:
From your  PC:
1. Clone this sample
2. Update the `.env` file with the values for your container registry and make sure that your docker engine has access to it
3. Build the entire solution by right-clicking on the `deployment.template.json` file and select `Build and push IoT Edge Solution` (this can take a while...especially to build open-cv, numpy and pillow...)

It need to run  3 docker file for CameraCapture.arm32v7 & SenseHatDisplay.arm32v7 & ImageClassifierService.arm32v7 image, 
When build CameraCapture.arm32v7 docker file , step5,6,7 will take 6 hours ,  only 70% compiled in 4 and a half hours, it is so slow. Can we improve performance for arm32v7 template?
![image](https://user-images.githubusercontent.com/35018765/52841842-49f17000-3138-11e9-8794-842e3c969ab2.png)

**Comment by adashen** [comment]
@czgtest  please add the issue to the custom vision repo. I will close it here since it is not edge tooling issue.
