### ISSUE TITLE
Show context menu in all *.template.json files

### ISSUE THREAD

**Issue by shizn** [Microsoft/vscode-azure-iot-edge#373]
![image](https://user-images.githubusercontent.com/3619378/53124901-7418a880-3511-11e9-8333-0e8df22317f5.png)

From  Hark Systems.

**Comment by shizn** [comment]
![image](https://user-images.githubusercontent.com/3619378/53125394-c3130d80-3512-11e9-9041-ddadeb6f9e70.png)

**Comment by adashen** [comment]
@czgtest please verify it on the latest release candidate

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/54505632-a03e1280-4973-11e9-8218-d4c876fc9561.png)

**Comment by adashen** [comment]
Will be consistent to only allow deployment.*.template.json

**Comment by czgtest** [comment]
fix work，only support deployment.*.template.json  in command line 
![image](https://user-images.githubusercontent.com/35018765/54732446-cd3a3180-4bce-11e9-9b97-f89ecd50eb67.png)

**Comment by czgtest** [comment]
edge new version 1.11.0 is support this feature，so close it
