### ISSUE TITLE
[ASA] Populate PlanId Env when adding ASA module

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#381]
Based on https://www.danielstechblog.io/stream-analytics-on-iot-edge-deployment-changes/ we need populate PlanId Env in the module setting now. And from portal setting module experience the value for the env is stream-analytics-on-iot-edge
linked from https://github.com/Azure/iotedgehubdev/issues/133

**Comment by SLdragon** [comment]
Fix and closed https://github.com/Microsoft/vscode-azure-iot-edge/pull/393
