### ISSUE TITLE
importing existing module from ACR wrongly appends if .env file is already open

### ISSUE THREAD

**Issue by stevebus** [Microsoft/vscode-azure-iot-edge#390]
- VSCode Version: 1.32.0
- OS Version:   win 10 1809
- Extension Version:  1.10.0

Steps to Reproduce:

1.   Have the .env file open, and the cursor having been left at the end of an existing line  (in my case, I had just added storage account name and key for the blob storage module and left the cursor there)
2.  import an existing module from a private ACR registry (which sets credentials for that registry in the .env file.

Obverve that the "CONTAINER_REGISTRY_USERNAME" gets appended to the end of an existing, unrelated line, rather than added on a newline, like this... 

STORAGE_ACCOUNT_KEY=adri74R3tAi1MlIRXXUo8g2niXSL925OMqibDjit/aXbEd9JToDxDsyFYI/tWbsRmw2B/9Udpq66F/+Evpv65A==CONTAINER_REGISTRY_USERNAME_stevebuscr=stevebuscr

I would expect the CONTAINER_REGISTRY_USERNAME to get added to a newline and not munged with the existing line

Does this issue occur when all other extensions are disabled?:   don't know, didn't try..  unrelated.

**Comment by adashen** [comment]
@stevebus , Thanks for reporting the issue. We will fix it in the next release.

**Comment by adashen** [comment]
@czgtest , please verify the fix on the latest release candidate

**Comment by czgtest** [comment]
code fix work on 1.11.0-rc2,verify pass

**Comment by adashen** [comment]
Close as fixed in 1.11.0
