### ISSUE TITLE
Bugbash - Peabody sample project experience in VS Code

### ISSUE THREAD

**Issue by Devinwong** [microsoft/vscode-azure-iot-edge#394]
- VSCode Version: 1.32.1
- OS Version: 17763
- Extension Version: Azure IoT Edge 1.10.2

Steps to Reproduce:

1. followed the steps by Xin
2. Press "Select folder" but nothing happened. Below are the output logs:
azure-iot-edge.showGallery: 
azure-iot-edge.initializeSample: 
azure-iot-edge.initializeSample: 
Cancelled by user
Cancelled by user
azure-iot-edge.initializeSample: 
Cancelled by user
azure-iot-edge.initializeSample: 
azure-iot-edge.initializeSample: 
Cancelled by user
azure-iot-edge.initializeSample: 
Cancelled by user
azure-iot-edge.initializeSample: 
Cancelled by user
azure-iot-edge.initializeSample: 
Cancelled by user

Showed to Renlong remotely and he is helping on this.

**Comment by adashen** [comment]
cannot reproduce now

**Comment by adashen** [comment]
Close since peabody experience is refreshed.
