### ISSUE TITLE
[Marketplace][Simulated Temperature Sensor] the routes and twins are incorrect

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#399]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for Simulated Temperature Sensor
2.In deployment.template.json and  deployment.debug.template.json, 
verify new module is added with properties: Routes Env Twins createOptions 

why add route "sensorToSimulatedTemperatureSensor" ?
the value is true for SendData instead of "true"
![image](https://user-images.githubusercontent.com/35018765/54341298-856a5600-4674-11e9-89f6-3cc35595396e.png)

marketplace deployment file
![image](https://user-images.githubusercontent.com/35018765/54341360-b5195e00-4674-11e9-89f6-3e82a2eb61eb.png)
expect format:  
https://gallery.azure.com/artifact/20161101/microsoft.edge-simulated-temperature-sensor-ga.1.0.10/Artifacts/Details.json

**Comment by formulahendry** [comment]
Duplicated with #397

**Comment by czgtest** [comment]
verify pass on 1.11.0-rc2
![image](https://user-images.githubusercontent.com/35018765/54414158-261f4b00-4733-11e9-853e-a19fcb9753b5.png)
