### ISSUE TITLE
[Marketplace]why add docker environmental variable in registryCredentials ?

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#400]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for SQL Server Module
2.In deployment.template.json and  deployment.debug.template.json, 
verify docker environmental variable is added in  registryCredentials, why add it?
"image": "microsoft/mssql-server-linux:2017-latest",
![image](https://user-images.githubusercontent.com/35018765/54345520-2e697e80-467e-11e9-88ab-77caaeedb898.png)

other marketplace module isn't add docker environmental variable

![image](https://user-images.githubusercontent.com/35018765/54345587-47722f80-467e-11e9-9623-5e3b2ef452d0.png)

**Comment by czgtest** [comment]
create new solution for Crosser IoT Edge Streaming Analytics
docker environmental variable is added too in registryCredentials node
Actually
![image](https://user-images.githubusercontent.com/35018765/54347120-4a225400-4681-11e9-90e3-bca23d62f8b8.png)
RegistryCredentials node is not added in marketplace deployment file
![image](https://user-images.githubusercontent.com/35018765/54347279-a8e7cd80-4681-11e9-922c-216a0c54da9f.png)

**Comment by czgtest** [comment]
Alleantia ISC Industry 4.0 edge gateway module has the same issue.

**Comment by czgtest** [comment]
Nebulus File Receiver
--
Nebulus Matrix Component
Nebulus Rules Engine
Nebulus Serial Port   Receiver
Nebulus SNMP Receiver
Nebulus UDP Receiver

**Comment by formulahendry** [comment]
https://github.com/Microsoft/vscode-azure-iot-edge/issues/342  

If it is `mcr.microsoft.com`, registryCredentials is expected not to append.

**Comment by formulahendry** [comment]
If it is acr, registryCredentials is expected to append.

**Comment by czgtest** [comment]
if it is microsoft. for example : microsoft/mssql-server-linux:2017-latest , is it expected to append

**Comment by formulahendry** [comment]
You could learn from https://hub.docker.com/r/microsoft/mssql-server-linux/
`microsoft/mssql-server-linux:2017-latest` and `testcase/samplemodule06:0.0.1-amd64` are treated as image on Docker Hub. Is expected to append.
