### ISSUE TITLE
[Marketplace][Crosser IoT Edge Streaming Analytics]Routes are not right

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#401]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for Crosser IoT Edge Streaming Analytics
2.In deployment.template.json and  deployment.debug.template.json, 
verify new module is added with properties: Routes Env Twins createOptions 
![image](https://user-images.githubusercontent.com/35018765/54347711-7ab6bd80-4682-11e9-817b-ec4563f9d293.png)

the route "sensorToCrosserIoTEdgeStreamingAnalytics" should be delete.
routes in marketplace deployment
![image](https://user-images.githubusercontent.com/35018765/54347763-9d48d680-4682-11e9-96f7-c233401e1f04.png)
expect format: 
https://gallery.azure.com/artifact/20161101/crosser.iot-edge-streaming-analyticsiot-edge-streaming-analytics.1.0.1/Artifacts/iot-edge-metadata.json

**Comment by formulahendry** [comment]
For every module added with new solution, there will be `sensorTo****` route, It is by design.

**Comment by czgtest** [comment]
by design ,  so close it.
