### ISSUE TITLE
[Marketplace][AVEVA IoT Edge HMI]the value of twins is inconsistent

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#402]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for AVEVA IoT Edge HMI
2.In deployment.template.json and  deployment.debug.template.json, 
verify new module is added with properties:  twins

actually:
![image](https://user-images.githubusercontent.com/35018765/54356500-c3787180-4696-11e9-994a-f0f4bf0481a7.png)

Expect in marketplate deployment json
![image](https://user-images.githubusercontent.com/35018765/54356557-ddb24f80-4696-11e9-8849-795b04204d75.png)

Expect format 
https://gallery.azure.com/artifact/20161101/aveva.iotviewmoduleiotview.1.0.2/Artifacts/iot-edge-metadata.json

**Comment by formulahendry** [comment]
Duplicated with #397

**Comment by czgtest** [comment]
verify pass on edge 1.11.0-rc2
![image](https://user-images.githubusercontent.com/35018765/54416969-da24d400-473b-11e9-974d-838897431c3d.png)
