### ISSUE TITLE
[Marketplace][Nebulus File Receiver]the value of PollingInterval is a number instead of a string

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#403]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for Nebulus File Receiver
2.In deployment.template.json and  deployment.debug.template.json, 
verify new module is added with properties:  twins
Actually:
the value of PollingInterval  is a string
![image](https://user-images.githubusercontent.com/35018765/54357418-ffacd180-4698-11e9-826d-86309e25f52f.png)

Expect in marketplace

![image](https://user-images.githubusercontent.com/35018765/54357496-2f5bd980-4699-11e9-8510-0ef9215d5db1.png)

**Comment by czgtest** [comment]
Nebulus Serial Port Receiver module has the same issue
actually
![image](https://user-images.githubusercontent.com/35018765/54361424-ef4d2480-46a1-11e9-9db0-e83ce0f4367e.png)
expect
![image](https://user-images.githubusercontent.com/35018765/54361458-02f88b00-46a2-11e9-9619-e700aec725b9.png)

**Comment by czgtest** [comment]
Nebulus SNMP Receiver module has the same issue too
actually
![image](https://user-images.githubusercontent.com/35018765/54362136-60d9a280-46a3-11e9-9569-514d7cdccd8d.png)
except
![image](https://user-images.githubusercontent.com/35018765/54362170-6e8f2800-46a3-11e9-9a0b-06b1dbf82543.png)

**Comment by czgtest** [comment]
Nebulus UDP Receiver also has this issue
actually
![image](https://user-images.githubusercontent.com/35018765/54362650-494ee980-46a4-11e9-82c9-7b7be7dc5226.png)
expect
![image](https://user-images.githubusercontent.com/35018765/54362666-51a72480-46a4-11e9-9ef5-d88bf7da92a7.png)

**Comment by formulahendry** [comment]
Duplicated with #397

**Comment by czgtest** [comment]
verify pass for Nebulus File Receiver
![image](https://user-images.githubusercontent.com/35018765/54417291-b4e49580-473c-11e9-9555-47327fbafdbe.png)

**Comment by czgtest** [comment]
Nebulus Serial Port Receiver module
![image](https://user-images.githubusercontent.com/35018765/54417867-4accf000-473e-11e9-837e-a55703616123.png)
Nebulus SNMP Receiver
![image](https://user-images.githubusercontent.com/35018765/54418091-dc3c6200-473e-11e9-8222-f29cfdeaf264.png)
Nebulus UDP Receiver 
![image](https://user-images.githubusercontent.com/35018765/54418230-3d643580-473f-11e9-9fe4-ae5c151c38ef.png)
