### ISSUE TITLE
[Marketplace][Nebulus Matrix Component]the format of twins is inconsistent

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#404]
- VSCode Version: 1.32.2
- OS Version: windows10
- Extension Version: 1.11.0-rc

Steps to Reproduce:

1.create new solution for Nebulus Matrix Component
2.In deployment.template.json and  deployment.debug.template.json, 
verify new module is added with properties:  twins

actually:
![image](https://user-images.githubusercontent.com/35018765/54358365-2ec44280-469b-11e9-81c8-5cf213eab671.png)

expect:
![image](https://user-images.githubusercontent.com/35018765/54358391-3ab00480-469b-11e9-8b79-13400b849864.png)

**Comment by czgtest** [comment]
Nebulus Rules Engine module has the same issue
actually
![image](https://user-images.githubusercontent.com/35018765/54358947-88793c80-469c-11e9-93d7-be544d6f7dca.png)
Expect:
![image](https://user-images.githubusercontent.com/35018765/54358976-94fd9500-469c-11e9-8ab1-3ebc605ae6bc.png)

**Comment by formulahendry** [comment]
Duplicated with #397

**Comment by czgtest** [comment]
verify pass for Nebulus Matrix Component
![image](https://user-images.githubusercontent.com/35018765/54417434-27ee0c00-473d-11e9-91a1-b0e33fad511f.png)

**Comment by czgtest** [comment]
verify pass for Nebulus Rules Engine module 
![image](https://user-images.githubusercontent.com/35018765/54417620-b1054300-473d-11e9-9639-efe5f5d357e1.png)
