### ISSUE TITLE
Module name should be allowed to start with number

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-edge#407]
Actual:
![image](https://user-images.githubusercontent.com/1050213/54503628-125e2980-496b-11e9-95ff-94136e59b1be.png)

Expect:
It is allowed in portal
![image](https://user-images.githubusercontent.com/1050213/54503675-2e61cb00-496b-11e9-93bb-6edb03c2f609.png)

Please check whether there is issue in the deploy template schema. @SLdragon

**Comment by SLdragon** [comment]
According to the schema, module names can only start with [a-zA-Z]

![image](https://user-images.githubusercontent.com/5545529/54509127-6bd25280-4983-11e9-86cd-9d98cf1d6018.png)

**Comment by SLdragon** [comment]
I will create a issue on schemastore

**Comment by adashen** [comment]
@czgtest  Please make sure this is fixed and close it.

**Comment by czgtest** [comment]
fix work now, so close it
![image](https://user-images.githubusercontent.com/35018765/54897270-a8adc480-4f02-11e9-964a-b03cf9373c88.png)
