### ISSUE TITLE
[marketplace] windows firewall has blocked some features of this app

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#411]
- VSCode Version: 1.32.3
- OS Version: VM 1809
- Extension Version: 1.11.0-rc2

Steps to Reproduce:

1. create new solution for marketplace
windows firewall has blocked some features of this app

![image](https://user-images.githubusercontent.com/35018765/54520948-d2b43380-49a4-11e9-8f0b-796d994eb4f8.png)
2.click Allow Access
3. the IoT edge marketplace page is display blank page

![image](https://user-images.githubusercontent.com/35018765/54521098-3179ad00-49a5-11e9-8b22-d5bab2dfc7d0.png)

**Comment by czgtest** [comment]
Azure IoT Edge: Show Sample Gallery  is also not work on VM

**Comment by formulahendry** [comment]
This issue is related to OS level firewall setting. No relates to extension itself. Close as external.

**Comment by formulahendry** [comment]
Open issue in VS Code repo: https://github.com/Microsoft/vscode/issues/70790
