### ISSUE TITLE
Edge sample gallery will open 3 tabs  in VS Code

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#414]
- VSCode Version:1.32.3
- OS Version:windows10
- Extension Version:1.10.0

Steps to Reproduce:

1. install vscode and edge extension
2. open sample gallery 3 times, the page will open 3 tabs  in VS Code, is it by design?
![image](https://user-images.githubusercontent.com/35018765/54655275-4b79d380-4afc-11e9-8e77-be676b67a08c.png)

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by adashen** [comment]
Will be fixed in next release

**Comment by adashen** [comment]
@czgtest please check the fix on the latest RC release

**Comment by czgtest** [comment]
fix work，will always display one page after open many times
