### ISSUE TITLE
Tell user about benefit of install iotedgehubdev

### ISSUE THREAD

**Issue by xinyiz1226** [Microsoft/vscode-azure-iot-edge#415]
- VSCode Version:
- OS Version:
- Extension Version:

Steps to Reproduce:

When user does not install iotedgehubdev, there is a window popped up to ask user to install. It will be better if message contains the info about why iotedgehubdev is needed, what benefit it can bring, etc.

**Comment by adashen** [comment]
@czgtest Please check and validate the issue on the latest RC build

**Comment by czgtest** [comment]
bellow scenarios will pop up a windows with message contain "for IoT edge simulator" .
1. when not install simualtor
![image](https://user-images.githubusercontent.com/35018765/56630175-0577d880-6683-11e9-9ae2-0a496c74c266.png)
2.when simulator need to upgrade
![image](https://user-images.githubusercontent.com/35018765/56630451-02311c80-6684-11e9-99a3-df86157aadbe.png)
3.when pip not install
![image](https://user-images.githubusercontent.com/35018765/56630730-d8c4c080-6684-11e9-828d-e05a4a917bc4.png)
4., when trigger a simulator related command
![image](https://user-images.githubusercontent.com/35018765/56630786-132e5d80-6685-11e9-96d6-9fedd21b4978.png)
