### ISSUE TITLE
the name of package does not match the pattern

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#416]
- VSCode Version:1.32.3
- OS Version: Windows10/Mac
- Extension Version: 1.11.0-rc2

Steps to Reproduce:

1.create new solution for Nodejs and input module name "SampleModuleNodejs"
2.open project and verify the name in the package.json 

![image](https://user-images.githubusercontent.com/35018765/54658685-9cdc8f80-4b09-11e9-8058-45af8fe2acc9.png)

**Comment by adashen** [comment]
@czgtest , what is the behavior in previous version?

**Comment by adashen** [comment]
Depends on node template fix

**Comment by adashen** [comment]
template fixed. Close the issue here
