### ISSUE TITLE
Do not generate env variables for username and password if module is imported from marketplace

### ISSUE THREAD

**Issue by xinyiz1226** [Microsoft/vscode-azure-iot-edge#417]
- VSCode Version:
- OS Version:
- Extension Version:

Steps to Reproduce:

1. select "Module from marketplace" when adding a module
2. select Redis module, or other modules hosted in marketplace.azurecr.io
3. CONTAINER_REGISTRY_USERNAME_marketplace & CONTAINER_REGISTRY_PASSWORD_marketplace will be generated in .env file, although this module is public and these two variables are not necessary

if we can confirm the modules from marketplace are all public, we don't have to generate variables

**Comment by czgtest** [comment]
![image](https://user-images.githubusercontent.com/35018765/54732882-36bb3f80-4bd1-11e9-8e51-13a1e8f535af.png)
