### ISSUE TITLE
context menu is not showing in deployment.chen#test.debug.amd64.json

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#421]
- VSCode Version:1.32.3
- OS Version: Windows10
- Extension Version: 1.11.0

Steps to Reproduce:
1. create new solution for c# module
2. rename deployment.debug.template.json  to deployment.chen#test.template.json
3. right-click deployment.chen#test.template.json to generate IoT edge deployment manifest
deployment.chen#test.arm32v7.json

4. right-click deployment.chen#test.arm32v7.json file
verify context menu is not display 
![image](https://user-images.githubusercontent.com/35018765/54897088-f970ed80-4f01-11e9-9b67-74127e462477.png)

expected:
below menu will dispaly

**Comment by czgtest** [comment]
deployment.chen#test.amd64.json file has the same issue

**Comment by czgtest** [comment]
deployment.chen--test.amd64.json too

**Comment by adashen** [comment]
@czgtest this is as designed. we will only show build/generate context menu on deployment.*.template.json

**Comment by czgtest** [comment]
@adashen  update the description of repro steps,  this is an issue need to fix

**Comment by adashen** [comment]
@czgtest Please check and test the issue on the latest RC build.

**Comment by czgtest** [comment]
fix work, context menu display well now
![image](https://user-images.githubusercontent.com/35018765/56629560-5b974c80-6680-11e9-9789-72e9a182ba18.png)
