### ISSUE TITLE
Be able to have multiple deployment.template.json files

### ISSUE THREAD

**Issue by viktoreinarsson** [Microsoft/vscode-azure-iot-edge#430]
I have only been able to run the deployment.template.json file in the simulator. The "Build and Run IoT Edge Solution in Simulator" context menu is missing in other files like deployment.template.deployment1.json.

Is this possible? We are setting up an environment where it´s possible to have different combinations of modules and it would be nice to be able to have multiple deployment.template.json files in the solution instead of changing the same one each time it´s needed.

**Comment by adashen** [comment]
@viktoreinarsson Thanks for the feedback!
Actually the latest version extension supports to have multiple template files with context menu. But please make sure the name of the template file is "deployment.*.template.json".

So in your case, please change the name to deployment.deployment1.template.json. Please have a try and let us know if it helps.

**Comment by viktoreinarsson** [comment]
Hey @adashen,

Thanks for the reply. It worked perfectly, thanks!

Is this documented somewhere? Might be nice to have documentation on this for example in here : https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module

**Comment by adashen** [comment]
@viktoreinarsson , Thanks for the suggestion. We will consider to update the documentation. And since the issue has been solved. I am closing here. If you find any other issue. Please feel free to open.
