### ISSUE TITLE
Windows IoT Edge modules not reporting connection state after long time

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#433]
- VSCode Version: any vs code
- OS Version: windows 10 rs5
- Extension Version: any version

Steps to Reproduce:

1. restart all Windows IoT Edge modules
2. wait for hours and check edge module connection state

**Comment by czgtest** [comment]
here is the latest result when restart IoT edge module in both simulator and edge runtime,

1.run IoT edge module in edge runtime, stop edge runtime and restart edge runtime, the connection state of module display well.
![image](https://user-images.githubusercontent.com/35018765/72044833-c6acb000-32ef-11ea-95c2-f70024ad747c.png)

2. run IoT edge module in simulator, stop simulator and restart simulator,Verify the icon of the device is changed to green, and has ‘Connected’ text
![image](https://user-images.githubusercontent.com/35018765/72046547-9ebf4b80-32f3-11ea-8a3c-bf7354cf36a4.png)

**Comment by czgtest** [comment]
wait for 10 hours and I check the connect state of module is "connected" 
![image](https://user-images.githubusercontent.com/35018765/72120244-4be8a100-3392-11ea-9ea1-54bcd18d0d0c.png)
