### ISSUE TITLE
scroll bar color is different from the VS Code theme

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#436]
![image](https://user-images.githubusercontent.com/3619378/56834346-05fca480-6826-11e9-8798-074e4189a8db.png)

**Comment by SLdragon** [comment]
Fixed: https://github.com/microsoft/vscode-azure-iot-edge/pull/522

**Comment by czgtest** [comment]
when color theme switch to Red/Solarized Dark/Tomorrow Night Blue/High contrast/Abyss...
scroll bar color is still different from the VS Code theme

**Comment by czgtest** [comment]
In VSCode, When the mouse is not in focus, the scroll bar will hidden,  but the scroll bar of gallery page is not hidden

**Comment by SLdragon** [comment]
@czgtest 
The sample gallery is similar with Extension README page, and we do not need to hide the scroll bar when it is not focused.

**Comment by czgtest** [comment]
make sense, so close it
