### ISSUE TITLE
Do not generate env variables for username and password if module is imported from mcr.microsoft.com

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#443]
- VSCode Version: 1.33
- OS Version: windows10
- Extension Version: 1.12.0

Steps to Reproduce:

1.create new solution for Azure Stream Analytics
2. the image of module is mcr.microsoft.com/azure-stream-analytics/azureiotedge:1.0.2
3.check .env file will be generated,  but it is not necessary

**Comment by adashen** [comment]
@czgtest please verify the fix on latest rc build

**Comment by czgtest** [comment]
fix work on edge v1.13.0-rc2, verify pass, so close it
