### ISSUE TITLE
Support .env file in module folder of VS edge project

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#448]
- VSCode Version: 1.33
- OS Version: Windows10
- Extension Version: 1.13.0-rc2

Steps to Reproduce:

1.Use Visual studio with edge exension version >= (v0.5 rc) to create a edge project with csharp module project.

2.Open the top folder of the above project in VSCode.

3.Navigate to folder of module.json file 

4.Update a module.json file in a module folder to reference some environment variables. For example, change the repository value to $REGISTRY/csharpmodule 

5.Create .env file at the same folder of module.json and set REGISTRY to localhost:5000 

6.Build the module image failed.

![image](https://user-images.githubusercontent.com/35018765/58066654-cf177580-7bbc-11e9-9db7-7f0217f07af8.png)

**Comment by czgtest** [comment]
the .env value will save in cache , when user change the value of .env,  then build IoT edge solution again,  it will user old value instead of new value, please see #452

**Comment by adashen** [comment]
@czgtest, please verify on 1.14.0-rc build. Not the env defined in sub module folder will override the one in solution folder

**Comment by czgtest** [comment]
fix work on 1.14.0-rc
Test scenario:
1.create .env file in module folder, 
REGISTRY=localhost:5000
2.Update a module.json file to $REGISTRY/csharpmodule
3.build IoT edge module pass

Test scenario2:
1.create .env file in module folder, 
REGISTRY=localhost:5000
2.Update a module.json file to $REGISTRY/csharpmodule
3.add .env file in solution folder
REGISTRY=czgregistry.azurecr.io
4.build IoT edge solution 
  verify the solution env will not override the one in module folder
![image](https://user-images.githubusercontent.com/35018765/59813454-20de2780-9344-11e9-9ec1-c1f6b48a9cdc.png)
