### ISSUE TITLE
Not support relate path module reference schema on Ubuntu/Mac

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#450]
- VSCode Version:1.33
- OS Version: Ubuntu/Mac
- Extension Version: 1.13.0-rc2

Steps to Reproduce:

1. Use Visual studio with edge exension version >= (v0.5 rc) to create a edge project with csharp module project. 
2. Open the top folder of the above project in VSCode. 
3. Navigate to the deployment.template.json file and make sure there is schema like ${MODULDIR<path>} reference to a module project. 
4. right-click deployment.template.json and select "Build and push IoT edge solution "
then it only generate deployment manifest, but not build docker image

expect: build and push docker image

**Comment by adashen** [comment]
This is path invalid issue, it is not the relative path issue

**Comment by czgtest** [comment]
when I change the image  from "${MODULEDIR<..\\IotEdgeModuleCsharp>}", to "${MODULEDIR<.../IotEdgeModuleCsharp>}", it work well on ubuntu and mac
