### ISSUE TITLE
Error building ARM32v7 on Unbuntu VSCODE 

### ISSUE THREAD

**Issue by pgupta408** [microsoft/vscode-azure-iot-edge#453]
Hi,

I am trying to build IoT module that I can deploy custom modules  on my Raspberry Pi running Raspian (as this is the only OS supported) which is connected to IoT-Hub using Azure IoTedge 

VSCode is configured for IoT-Hub 

I am able to build for amd64 using VScode. No problem.

However, I am facing major problem when I am trying to build for arm32v7. Please help. 

ubuntu@ubuntu-Mobilestack:~/Desktop/MobilestackEdgeSolution/modules/EdgeSolution1$ docker build  --rm -f "/home/ubuntu/Desktop/MobilestackEdgeSolution/modules/EdgeSolution1/modules/SampleModule/Dockerfile.arm32v7" -t mobilestack.azurecr.io/samplemodule:0.0.1-arm32v7 "/home/ubuntu/Desktop/MobilestackEdgeSolution/modules/EdgeSolution1/modules/SampleModule" && docker push mobilestack.azurecr.io/samplemodule:0.0.1-arm32v7
Sending build context to Docker daemon  19.97kB
Step 1/14 : FROM arm32v7/ubuntu:xenial AS base
 ---> ce53195c6905
Step 2/14 : RUN apt-get update &&     apt-get install -y --no-install-recommends software-properties-common &&     add-apt-repository -y ppa:aziotsdklinux/ppa-azureiot &&     apt-get update &&     apt-get install -y azure-iot-sdk-c-dev &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 00d50daf3694
standard_init_linux.go:207: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends software-properties-common &&     add-apt-repository -y ppa:aziotsdklinux/ppa-azureiot &&     apt-get update &&     apt-get install -y azure-iot-sdk-c-dev &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

I am getting "exec format error" which is generally seen due to architecture mismatch. 

I have selected arm32v7 as target. 

What is the problem?  

Please help solve.

**Comment by adashen** [comment]
@pgupta408 , Thanks for reporting the issue. If you want to build an arm32v7 image, please use an arm32v7 device (for example raspberry pi). Docker does not support building arm32v7 image on an amd64 device. 

After you setting up the docker env on the arm32v7 device, you could refer to https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/
for detail to use vscode to connect the remote docker engine

**Comment by pgupta408** [comment]
I did connect to remote Raspberry-Pi and configured arm32v7 as target. 

VScode was running on Amd64 m/c in linux 16.04. 

It failed.  So, your response below is not of much help. 

Just to test if I can build and deploy AMD64 module, I tried building AMD target as well and it worked. 

Thanks

On May 27, 2019, at 10:05 PM, Wei Shen <notifications@github.com> wrote:

@pgupta408 , Thanks for reporting the issue. If you want to build an arm32v7 image, please use an arm32v7 device (for example raspberry pi). Docker does not support building arm32v7 image on an amd64 device.

After you setting up the docker env on the arm32v7 device, you could refer to https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/
for detail to use vscode to connect the remote docker engine

**Comment by adashen** [comment]
@pgupta408 , can you try the following step?
1. In the vscode terminal, run "echo $DOCKER_HOST" to check whether your current docker client connects to the raspberrypi? 
2. Copy your module project to raspberry pi and just docker build the image on the raspberry pi natively, to make sure the raspberry pi docker env is correctly working.

Since arm32v7 are not supported to be built on amd64 machine. So we need to set DOCKER_HOST and related envs to connect a docker daemon running on the remote raspberrypi. When build the the module image docker will respect the docker env and ask the remote daemon to build the image.

**Comment by pgupta408** [comment]
Hi,

 

Already tried building module directly on Docker in Raspberry Pi. It builds fine. But, after deployment, I am not able to get localhost web access for running module due to Microsoft IoT-Edge network configuration for Docker at Edge. 

 

I had googled your article and tried to follow it already. However, I do not remember using SSH without password for remote connection to IoT-Edge.  I will try these steps. 

 

BTW, I am trying to deploy Zigbee Driver & Edge application in this project. In case you want to try, let me know. I can provide Github URL for this. 

 

Thanks

-Praveen

https://www.mobilestack.com <https://www.mobilestack.com/> 

 

Article:-

Ten steps of adding LTE to a Wearable -  <https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/> https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/

5G Pillars for network densification - https://www.mobilestack.com/blog/5g-infrastructure-pillers-for-densification/

5G for Cable Industry -  <https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/> https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/

5G in India -   <https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/> https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/

 <https://www.mobilestack.com/> 

Follow us at:   <https://twitter.com/mobilestackinc>  <https://www.linkedin.com/company/Mobilestack-inc>   <https://www.facebook.com/MobilestackInc/> 

This e-mail message, and any attachments, is intended only for the use of the individual or entity identified in the alias address of this message and may contain information that is confidential, privileged and subject to legal restrictions and penalties regarding its unauthorized disclosure and use. Any unauthorized review, copying, disclosure, distribution or use is strictly prohibited. If you have received this e-mail message in error, please notify the sender immediately by reply e-mail and delete this message, and any attachments, from your system. Thank you for your cooperation.

**Comment by shizn** [comment]
@pgupta408 definitely would love to learn this project and see how I can help. Could you just involve myself there?

**Comment by pgupta408** [comment]
Is it possible to have a debug session together? 

I am trying to deploy DECONZ docker via iotedge:
https://github.com/marthoc/docker-deconz

Your documentation is highly convoluted.

Sent from Mail for Windows 10

**Comment by pgupta408** [comment]
Hi Wei

 

I do NOT see a good way to setup environment variables that you have mentioned in article and how to setup $DOCKER_HOST variable properly.. 

 

I see Docker:Host option to set. But, this require host-address and port-id only. Not a JSON way to setup as mentioned in your blog. 

 

Is there a way to do an online session together to solve this? 

 

Thanks

-Praveen

https://www.mobilestack.com <https://www.mobilestack.com/> 

 

Article:-

Ten steps of adding LTE to a Wearable -  <https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/> https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/

5G Pillars for network densification - https://www.mobilestack.com/blog/5g-infrastructure-pillers-for-densification/

5G for Cable Industry -  <https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/> https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/

5G in India -   <https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/> https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/

 <https://www.mobilestack.com/> 

Follow us at:   <https://twitter.com/mobilestackinc>  <https://www.linkedin.com/company/Mobilestack-inc>   <https://www.facebook.com/MobilestackInc/> 

This e-mail message, and any attachments, is intended only for the use of the individual or entity identified in the alias address of this message and may contain information that is confidential, privileged and subject to legal restrictions and penalties regarding its unauthorized disclosure and use. Any unauthorized review, copying, disclosure, distribution or use is strictly prohibited. If you have received this e-mail message in error, please notify the sender immediately by reply e-mail and delete this message, and any attachments, from your system. Thank you for your cooperation.

**Comment by adashen** [comment]
@pgupta408 , To set any environment variable to the vscode edge extension. You could config the workspace setting with key "azure-iot-edge.executor.env" and add environment variables. 

1. Open command palette "Preference: Open User Settings".
2. Switch to "Workspace Settings"
3. You may edit the settings in JSON style (settings.json) 
4. Add  and config the env in "azure-iot-edge.executor.env". For example
    "azure-iot-edge.executor.env": {
        "DOCKER_HOST": "XXXX"
    }

**Comment by pgupta408** [comment]
This was already tried..  Not sure why environment variable is not available in terminal window. 
At this point,  Module builds for arm32v7.. But, does NOT deploy on target RaspberryPi

Here is Screenshot:



Sent from Mail for Windows 10

**Comment by adashen** [comment]
@pgupta408, it seems you would like to deploy the edge solution to the rasperberry pi right? 
If that is the case did you successfully iot edge runtime on the pi first? And you also need to push the image and make a deployment to the runtime.

As for the docker ENV configuration in VSCode "azure-iot-edge.executor.env", it is used to help to build docker images on remote daemon. They are not related to do edge deployment.

**Comment by pgupta408** [comment]
Obviously, I have IoT-edge deployed and working on Pi. 

Why I am not able to deploy? It seems that build is going through on Windows-10 development m/c. 
It still fails when I use x86 Ubuntu based development m/c. 

Also, how to deploy a docker built module or docker hub module using Microsoft IoT edge?

Thanks

On Jun 5, 2019, at 1:01 AM, Wei Shen <notifications@github.com> wrote:

@pgupta408, it seems you would like to deploy the edge solution to the rasperberry pi right?
If that is the case did you successfully iot edge runtime on the pi first? And you also need to push the image and make a deployment to the runtime.

As for the docker ENV configuration in VSCode "azure-iot-edge.executor.env", it is used to help to build docker images on remote daemon. They are not related to do edge deployment.

**Comment by adashen** [comment]
Hi, @pgupta408 , to deploy to an edge devices，we need make sure the module images has been successfully pushed to the target container registry. Since you are using raspberry pi, the most direct way is do it from the raspberry pi through docker build and push the images to registry (using docker cli)
After that, you can deploy the edge solution. And please refer to https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux for the deployment step.

If you would like to build and push from VSCode on your windows desktop，
1. you need correctly setup remote docker host to open connection ports and maybe install certificates.  And then you can add the related docker environment variables to vscode edge configuration.  
2. in "azure-iot-edge.executor.env". For example
"azure-iot-edge.executor.env": {
"DOCKER_HOST": "XXXX"
}
After setting the configuration please reload the window to take effect. 
3. Use command "Set Default Target Platform for Edge Solution" from command palette to switch the default platform to arm32v7.

And the steps could be found at https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/

**Comment by pgupta408** [comment]
The intent is to do DevOps from VScode. 

I have followed all three steps that you have mentioned.  I am able to build via VSCode for target platform .. But, I am not able to deploy. 

Thanks

On Jun 10, 2019, at 9:57 PM, Wei Shen <notifications@github.com> wrote:

Hi, @pgupta408 , to deploy to an edge devices，we need make sure the module images has been successfully pushed to the target container registry. Since you are using raspberry pi, the most direct way is do it from the raspberry pi through docker build and push the images to registry (using docker cli)
After that, you can deploy the edge solution. And please refer to https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux for the deployment step.

If you would like to build and push from VSCode on your windows desktop，

you need correctly setup remote docker host to open connection ports and maybe install certificates. And then you can add the related docker environment variables to vscode edge configuration.
in "azure-iot-edge.executor.env". For example
"azure-iot-edge.executor.env": {
"DOCKER_HOST": "XXXX"
}
After setting the configuration please reload the window to take effect.
Use command "Set Default Target Platform for Edge Solution" from command palette to switch the default platform to arm32v7.
And the steps could be found at https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/

**Comment by adashen** [comment]
@pgupta408 , you can deploy in vscode with command "Azure IoT Edge: Create Deployment for Single Device". It will as you to choose the target device and the deployment manifest. 
As for the deployment manifest, it could be generated during build the edge solution or trigger "Azure IoT Edge: Generate IoT Edge Deployment Manifest".

**Comment by pgupta408** [comment]
Now, my free subscription of Azure has expired.  

 

Help in getting Azure subscription extended is possible. 

 

Thanks

-Praveen

https://www.mobilestack.com <https://www.mobilestack.com/> 

 

Products:

5G Mobilestack Products:  <https://www.mobilestack.com/blog/mobilestack-5g-products/> https://www.mobilestack.com/blog/mobilestack-5g-products/

 

Article:-

Ten steps of adding LTE to a Wearable -  <https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/> https://www.mobilestack.com/blog/ten-steps-of-adding-lte-to-a-wearable/

5G Pillars for network densification - https://www.mobilestack.com/blog/5g-infrastructure-pillers-for-densification/

5G for Cable Industry -  <https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/> https://www.mobilestack.com/blog/5g-business-opportunity-for-cable-industry/

5G in India -   <https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/> https://www.mobilestack.com/blog/5g-in-india-need-to-create-new-public-private-partnership-projects/

Video:

SDR-based Private LTE demo - https://www.youtube.com/watch?v=ZyGyreFG5wI

Intelligent Edge GW Demo – coming soon

 

 <https://www.mobilestack.com/> 

Follow us at:   <https://twitter.com/mobilestackinc>  <https://www.linkedin.com/company/Mobilestack-inc>   <https://www.facebook.com/MobilestackInc/> 

This e-mail message, and any attachments, is intended only for the use of the individual or entity identified in the alias address of this message and may contain information that is confidential, privileged and subject to legal restrictions and penalties regarding its unauthorized disclosure and use. Any unauthorized review, copying, disclosure, distribution or use is strictly prohibited. If you have received this e-mail message in error, please notify the sender immediately by reply e-mail and delete this message, and any attachments, from your system. Thank you for your cooperation.

**Comment by adashen** [comment]
Close the issue since no recent response and the original build arm32v7 issue is solved.
