### ISSUE TITLE
Run command failed on VSCode 1.35.0

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-azure-iot-edge#459]
- VSCode Version: 1.35.0

Steps to Reproduce:

1. Build and Push/ Build and Run solution will fail on 1.35.0 because of the broken change in vscode
https://github.com/microsoft/vscode/blob/5c65d9bfa4c56538150d7f3066318e0db2c6151f/src/vs/workbench/contrib/terminal/node/terminal.ts#L12-L55

Work around: set "terminal.integrated.shell.windows": "powershell" in user settings of vscode.

**Comment by apulliam** [comment]
May want to do the workaround in workspace settings.  The "terminal.integrated.shell.windows": "powershell" setting breaks the latest Azure Functions extension.  It causes a hang when trying to debug.  Repro by creating an Azure Functions project with the extension.  Add the setting.  Hit Debug run.

**Comment by adashen** [comment]
@apulliam just updated the workaround, we need to update the value to the path to powershell. And we will have a new version of extension released in this week. After the new release the workaround is not needed.

**Comment by adashen** [comment]
@czgtest Please verify on 1.14.0-rc build

**Comment by czgtest** [comment]
vscode: v1.35.1
edge:1.40.0-rc
fix work and verify pass on windows, 
![image](https://user-images.githubusercontent.com/35018765/59812095-546a8300-933f-11e9-8a79-3d5660d263d6.png)
