### ISSUE TITLE
invalid image placeholder

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#466]
- VSCode Version: 1.35.1
- OS Version: windows10
- Extension Version:1.40.0-rc

Steps to Reproduce:

1.create Empty solution
2.add C module
 invalid image placeholder in deployment.template.json
![image](https://user-images.githubusercontent.com/35018765/59808203-d356c000-932d-11e9-9006-d36684be3bff.png)

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by adashen** [comment]
@czgtest please check the default platform, whether it is supported by the c module. if not, it is as designed and please close it.

**Comment by czgtest** [comment]
if select the platform to windows-amd64 , it will display invalid image placeholder, it is by design so close it
