### ISSUE TITLE
[Mac] Remote debug C module cannot hit break point

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#468]
- VSCode Version: 1.35.0
- OS Version: Mac
- Extension Version: 1.14.0

Steps to Reproduce:

1.create C module in vscode
2. build and run IoT edge in simulator for amd64-debug
3.check D2C message is receiving
4.remote debug C module , but breakpoint can't hit and cannot open source file in C.main file.
![image](https://user-images.githubusercontent.com/35018765/59913979-e8297580-944b-11e9-8b21-dc0476c4da2f.png)

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by czgtest** [comment]
this is known issue , https://github.com/microsoft/vscode-cpptools/issues/2444 is pending release

**Comment by adashen** [comment]
https://github.com/microsoft/vscode-cpptools/issues/3434 maybe related @formulahendry please have a check
