### ISSUE TITLE
ARM64 module Dockerfiles

### ISSUE THREAD

**Issue by sebader** [microsoft/vscode-azure-iot-edge#486]
Now that IoT Edge 1.0.8 is out which supports ARM64, you should add Dockerfiles to build images for that in the module templates.

**Comment by blackchoey** [comment]
Hi @sebader We're working to add ARM64 templates. dotnet arm64 template (preview) is already available. Please refer following blog post to try the dotnet arm64 module: https://devblogs.microsoft.com/iotdev/develop-and-debug-arm64-iot-edge-modules-in-visual-studio-code-preview/

**Comment by blackchoey** [comment]
@sebader We have updated following blog to introduce how to create arm64 project for all languages (except python, which has some issues with the SDK): https://devblogs.microsoft.com/iotdev/develop-and-debug-arm64-iot-edge-modules-in-visual-studio-code-preview/. I'm going to close this issue. Feel free to open new issues if you would like to discuss other topics.
