### ISSUE TITLE
Guide use to setup device connection string when Set module credentials to user settings

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#489]
- VSCode Version: latest 
- OS Version:  windows10
- Extension Version: 1.16.0-rc

Steps to Reproduce:
1. Install iotedgehubdev and make sure its version >= 0.10.0 
2. Remove config file of iotedgehubdev 
3. Create an edge solution and try to run “Set module credentials to user settings” 
actually : you can see bellow error 
![image](https://user-images.githubusercontent.com/35018765/62750131-8b345e00-ba91-11e9-8539-2d0cce1e6070.png)

Expect: would see waring window on the right bottom of VSCode 
![image](https://user-images.githubusercontent.com/35018765/62750167-b028d100-ba91-11e9-8edd-d1fcf8c5ddbe.png)

**Comment by marianan** [comment]
Issue is resolved in v1.23.0.
