### ISSUE TITLE
Open "Vision AI Developer Kit" gallery sample need 2-3 minutes

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#490]
- VSCode Version:
- OS Version:
- Extension Version:

Steps to Reproduce:

1. Show Sample Gallery 
2. click "Open Sample" for Vision AI Developer Kit 

user need to wait 2-3 minutes to open it .

**Comment by SLdragon** [comment]
Thanks, it is because this repo is large, and clone it from github would take about 2~3 minutes, I will create an issue (https://github.com/microsoft/vision-ai-developer-kit/issues/213) on vision-ai-developer-kit repo and in add a task to show progress from our extension.

**Comment by adashen** [comment]
Sample issue so close in this repo
