### ISSUE TITLE
windows message has a syntax error

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#496]
- VSCode Version: 1.37.1
- OS Version: windows10
- Extension Version: v1.17.0-rc

Steps to Reproduce:

1. create new solution for ASA module
2. open deployment.template.json file  and click "check configuration update for ASA job"
it would pop up windows message "No configuration changes **has** been found for Stream Analytics Job"
but this message has a syntax error .  can we use bellow message?

No configuration changes **have** been found for Stream Analytics Job
or 
No configuration changes were found for Stream Analytics Job

**Comment by adashen** [comment]
@czgtest it should be fixed in the released version. Please check and close.

**Comment by czgtest** [comment]
fix work , so close it.
![image](https://user-images.githubusercontent.com/35018765/65104513-37a81f00-da04-11e9-83c1-c2cc02711867.png)
