### ISSUE TITLE
Use docker environment variable in Azure Function edge module

### ISSUE THREAD

**Issue by RudyEvers** [microsoft/vscode-azure-iot-edge#502]
Hi,

I am working on a Azure IoT Edge project and I cannot figure out how to get custom docker environment variables in my C# class.
 
So I have Azure Functions running as a module on a IoT Edge environment. On this Edge environment also Azure Blob Storage is running as a module. The Azure Function has to get some information from a blob container. At the moment Blob connection string is hard coded, but with the possibility of having more Edge environment I want to be able to set this connection string through the docker environment variable. 

So when I create a new Edge device in Azure and add a Function Module the connection string of the Blob storage must be set via a Environment Variable. 
Can't find any documentation how to achieve this. Is it possible?

![azure function module](https://user-images.githubusercontent.com/38738862/65147412-603d1280-da1e-11e9-925d-416d2ce557c7.PNG)

**Comment by adashen** [comment]
@RudyEvers are you trying to figure out how to set environment variables in VS Code for custom module? Here is the steps.
1. Open your deployment template in VSCode.
2. And add the env for your custom module at
```json
"customodule": {
    "type": "docker",
    "settings": {
        "image":  "<image>"
        "createOptions": ""
    }
    "env": {
        <YOUR_ENV>: {
            "value": <ENV_VALUE>
        }
    }
}
```

**Comment by adashen** [comment]
Close the issue as there is no more comment from customer

**Comment by adashen** [comment]
Please feel free to open when you have more questions

**Comment by RudyEvers** [comment]
Got it all working. Thank you
