### ISSUE TITLE
Implement Dispose pattern on Message send to output (C# templates)

### ISSUE THREAD

**Issue by sandervandevelde** [microsoft/vscode-azure-iot-edge#503]
In the C# module template and the C# function template, a message is constructed:

`var pipeMessage = new Message(messageBytes);`

The Message class implements the Dispose method. The Message class must follow the Dispose pattern to ensure it's disposed in all paths.

with 'using()' we can enforce the Dispose pattern.

This is also in sync with eg. the https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module documentation.

ps. I was not able to find the templates. Are these available on github too?

**Comment by czgtest** [comment]
@sandervandevelde , Here is the git hub resource of C# module and C# function .  

C#: https://github.com/azure/dotnet-template-azure-iot-edge-module/
C# function: https://github.com/azure/dotnet-template-azure-iot-edge-function/

**Comment by sandervandevelde** [comment]
Thanks. I will check these out.

**Comment by adashen** [comment]
Since the issue will be handled in template repo. Close in this repo.
