### ISSUE TITLE
Tags will be empty in Marketplace page when cancel the import.

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#508]
- VSCode Version:
- OS Version:
- Extension Version:v1.18.0-rc

Steps to Reproduce:

1. create new project for marketplace
2. select NVIDIA DeepStream SDK
3. switch plans and tags to another one
4. cancel the page
5. select NVIDIA DeepStream SDK again
verify the tags will display well.
6. cancel the page again
7. select NVIDIA DeepStream SDK again
verify the tags is empty 
![image](https://user-images.githubusercontent.com/35018765/67663952-96689d00-f9a1-11e9-93e4-aa22cc1ccba5.png)

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by formulahendry** [comment]
Fixed in https://github.com/microsoft/vscode-azure-iot-edge/releases/download/v1.18.0-rc2/azure-iot-edge-1.18.0-rc2.vsix
please help verify, thanks!
