### ISSUE TITLE
Reminder user to run "Azure IoT Edge: Setup IoT Edge Simulator" instead of "iotedgehubdev setup -c"

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#517]
Repro on v1.19.0-rc

step: 
1. now it will auto-install  simulator on clean VM 
user don't know the location of simulator by default
2. run IoT edge solution in simulator
3. here will reminder user to run command `iotedgehubdev setup -c "<edge-device-connection-string>"` first.
if user run iotedgehubdev setup -c "<edge-device-connection-string>" manually , he will get error

**so we can ask user to Press F1 or Ctrl + Shift + P to open command palette and run "Azure IoT Edge: Setup IoT Edge Simulator"** 

![image](https://user-images.githubusercontent.com/35018765/68748202-f4021800-0636-11ea-9091-fcbac579494b.png)

**Comment by SLdragon** [comment]
Thanks, good point!

**Comment by czgtest** [comment]
when Azure IoT Edge: Start IoT Edge Hub Simulator for Single Module, it will pop up message , click setup ,then it will auto-call "Azure IoT Edge: Setup IoT Edge Simulator"

![image](https://user-images.githubusercontent.com/35018765/68748954-63c4d280-0638-11ea-9765-fb61b862ca1c.png)

**Comment by czgtest** [comment]
when run "Azure IoT Edge: Set Module Credentials to User Settings"  

![image](https://user-images.githubusercontent.com/35018765/68914221-e5337680-0798-11ea-986a-ea75ba339a9d.png)

**Comment by czgtest** [comment]
Fix work, so close it
