### ISSUE TITLE
Dockerfiles: Moving from microsoft/dotnet:2.1-sdk to mcr.microsoft.com/dotnet/core/sdk:2.1

### ISSUE THREAD

**Issue by kiranpradeep** [microsoft/vscode-azure-iot-edge#520]
The module Dockerfiles base images (sdk/runtime) are not suggested in dockerhub anymore. This creates some ambiguity. Can you please migrate from microsoft/dotnet to new dockerhub repo as in mcr.microsoft.com ?

Kindly guide if the repo is not appropriate. I raised here since there was a similar [issue](https://github.com/microsoft/vscode-azure-iot-edge/issues/93).

**Comment by adashen** [comment]
@kiranpradeep Thanks for the suggestion. We will follow up and update the template. When the template is updated, it will automatically be shown in the extension.

**Comment by kiranpradeep** [comment]
@adashen Thanks. Out of curiosity: Should I have raised this ticket at [templates](https://github.com/Azure/dotnet-template-azure-iot-edge-module) repo?

**Comment by adashen** [comment]
https://github.com/Azure/dotnet-template-azure-iot-edge-module/issues/69 added issue in templates repo

**Comment by adashen** [comment]
Issue tracked in template repo. so close here.
