### ISSUE TITLE
VSCode debug hang executing remoteProcessPickerScript remotely

### ISSUE THREAD

**Issue by RotateAt60MPH** [microsoft/vscode-azure-iot-edge#528]
- VSCode Version: 1.41.1
- VSCode OS Version: Windows 10 Pro x64
- IoT Edge OS Version: rPI4 running Raspian Buster  
- Extension Version:  
Azure IoT Edge for VSCode 1.20
Azure Iot Tools 0.3.0

Debugging hangs when VSCode attempts to run remoteProcessPickerScript against ioT Edge machine.

Steps to Reproduce:

1. Followed the steps at https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes.  Have key-based login to rPI4 IoT Edge computer running Raspian.  Installed vsdbg, per instructions.
2. Successfully tested: ssh pi@10.168.1.229 echo "Hello World"
3. Created workspace with 2 modules (DataModule and SampleModule).  Uses SimulatedTemperatureSensor module
3. Built and Push following deployment.template.json:

```
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "cccregistry": {
                "username": "$CONTAINER_REGISTRY_USERNAME_cccregistry",
                "password": "$CONTAINER_REGISTRY_PASSWORD_cccregistry",
                "address": "cccregistry.azurecr.io"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "SampleModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.SampleModule}",
              "createOptions": {}
            }
          },
          "SimulatedTemperatureSensor": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": {}
            }
          },
          "DataModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.DataModule}",
              "createOptions": {}
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "SampleModuleToIoTHub": "FROM /messages/modules/SampleModule/outputs/* INTO $upstream",
          "sensorToSampleModule": "FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint(\"/modules/SampleModule/inputs/input1\")",
          "DataModuleToIoTHub": "FROM /messages/modules/DataModule/outputs/* INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}

```
4. Created debug configuration in launch.json:
```
{
  "version": "0.2.0",
  "logging": {
    "engineLogging": true
  },
  "configurations": [
    {
      "name": ".NET Core SSH Attach",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:pickRemoteProcess}",
      "pipeTransport": {
          "pipeProgram": "ssh",
          "pipeArgs": [ "-T", "pi@10.168.1.229" ],
          "debuggerPath": "~/vsdbg/vsdbg",
          "pipeCwd": "${workspaceRoot}",
          "quoteArgs": true
      },
      "sourceFileMap": {
          "/home/pi/EdgeSolution": "${workspaceRoot}"
      }
  }
  ]
}
```
5. Created Deployment for Single Device to IoT Edge device.
6. Set breakpoint in SampleModule Program.cs.  Selected 'NET Core SSH Attach' in debug dropdown
7. See this in Output window:
`Executing: ssh -T pi@10.168.1.229 "sh -s" < C:\Users\wirunc\.vscode\extensions\ms-vscode.csharp-1.21.9\scripts\remoteProcessPickerScript`
8. Debugging is now hung.  See processes on IoT Edge device.  When reboot IoT Edge device, additional message in Output pane (i.e. it was connected):
`stderr: Connection to 10.168.1.229 closed by remote host.`

9. Manually run the command in step 7 in Git Bash shell and shows list of processes.
10. Manually run the above command from 'x64 Native Command Prompt DOS' shell and it hangs, like it does in VSCode.

```Does this issue occur when all other extensions are disabled?: Yes

**Comment by czgtest** [comment]
@RotateAt60MPH, you can follow the instructions in this [blog.] (https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/)  to debug IoT edge module on raspberry Pi.
now there is an issue [3347](https://github.com/OmniSharp/omnisharp-vscode/issues/3347 ) for C# extension , not support "-H ssh://pi@ipaddress" .
if you use "-H tcp://piaddress:2375" to debug IoT module, it work well. bellow is some steps:

Setup raspberrypi:
1.	Add “-H tcp://0.0.0.0:2375” to docker deamon
sudo nano /lib/systemd/system/docker.service
sudo systemctl daemon-reload
sudo systemctl restart docker
2.	Install edge runtime

Test on Windows:
1.	Create C# module with ACR
2.	Set docker host in user settings
"DOCKER_HOST": "tcp://40.78.65.87:2375"
3.	Build and run IoT edge solution for amd64.debug
4.	Add "-H tcp://40.121.83.147:2375" to PipeArgs 
5.	Create deployment for single module.
6.	Remote debug and break point can be hit

**Comment by RotateAt60MPH** [comment]
Thanks @czgtest.  worked perfectly.
