### ISSUE TITLE
Unable to compile using RPi.GPIO using VS Code

### ISSUE THREAD

**Issue by orionJag** [microsoft/vscode-azure-iot-edge#534]
- VSCode Version: 1.43.1 
- OS Version:  Linux rasxyz 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Extension Version:

Additional Info:  
1. Hardware RPI4 

2. OS
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

3. Libraries in requirements.txt 
azure-iot-device~=2.0.0
RPi.GPIO
mfrc522

Steps to Reproduce:
1. Create an IoT Edge Python module using RPi.GPIO 
2. Issue a Build & Push IoT Edge Solution 

Does this issue occur when all other extensions are disabled?:  Not sure 
[RPI4_Module_compile_msg.txt](https://github.com/microsoft/vscode-azure-iot-edge/files/4356632/RPI4_Module_compile_msg.txt)

It appears, the VSC is issuing pip install of requirements.txt despite an alias was setup in the  "~/.bashrc" for pip3 and python3 

I have a similar standalone python script using these libraries and it is working perfectly fine but it's  not as IoT edge module but purely sending the telemetry to IoT Hub

Hopefully this is some sort of setup issue in VSC on my PC /RPI4  and hopefully helps others in trying to find a solution.  

Appreciate everyone's help and support.

**Comment by blackchoey** [comment]
@orionJag The module is built in docker, which means the environment on your dev machine won't impact the build commands. The base image `python:3.7-slim-buster` used in the default dockerfile does not contain gcc, which resulted the error you met. You can add one step in dockerfile to install gcc in order to fix this error.

**Comment by orionJag** [comment]
Thanks for the quick response. Could you please let me know process / command to install gcc using VSC.

**Comment by blackchoey** [comment]
Just find commands that installs gcc on Ubuntu and add the commands to dockerfile (before pip install command). Here's one tutorial I found, just for your information: https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/
VSC does not take part in gcc installation.

**Comment by orionJag** [comment]
Issue resolved after adding the following lines to the docker file 

RUN apt-get update -y
RUN apt install build-essential -y 
RUN apt-get install manpages-dev -y
