### ISSUE TITLE
[Doc] pip link is empty

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-edge#54]
![image](https://user-images.githubusercontent.com/1050213/37507471-94c03ae8-2929-11e8-99b7-42cc70f591c6.png)

Better to use this link: https://pip.pypa.io/en/stable/installing/#installation

**Comment by adashen** [comment]
Fixed in page https://review.docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?branch=pr-en-us-35471
