### ISSUE TITLE
"invalid signtaure" blocking update

### ISSUE THREAD

**Issue by rpus** [microsoft/vscode-azure-iot-edge#542]
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

Azure IoT extension version 1.21.0

Steps to Reproduce:

1. Start up VS Code and wait for Azure IoT Edge extension to try updating/downloading
2. See this in console output:
```
Task failed with error: Cannot extract simulator binaries from zip file: invalid signature: 0x6d74683c, wait 5000 milliseconds and retry (1)...
Task failed with error: Cannot extract simulator binaries from zip file: invalid signature: 0x6d74683c, wait 5000 milliseconds and retry (2)...
Task failed with error: Cannot extract simulator binaries from zip file: invalid signature: 0x6d74683c, wait 5000 milliseconds and retry (3)...
Failed to install 'iotedgehubdev' tool because of error: Cannot extract simulator binaries from zip file: invalid signature: 0x6d74683c
```

NB: I do not know what the correct signature is (or even what it is the signature of)! Anyway, I have lots of other extensions, and they all update fine regularly, **even when** (like C# or MSSQL) they end up downloading various extra components. I am behind a corporate proxy, but as I say, all my other extensions seem to work/update/**download extras** fine.

PS: See here in case it helps! https://github.com/microsoft/vscode/issues/12588#issuecomment-530719673

**Comment by SLdragon** [comment]
Hi, @rpus , our extension using github release page to host the simulator binaries, from your error messages, seems like the zip file downloaded from github is corrupt. 

Not sure whether it is related to the proxy, so you can manually to download the zip file here to see whether the zip file is fine:
https://github.com/Azure/iotedgehubdev/releases/download/v0.13.0/iotedgehubdev-v0.13.0-win32-ia32.zip

If the zip file is fine, you remove the extension, clear the extension folder (C:\Users\[YourUserName]\.vscode\extensions\vsciot-vscode.azure-iot-edge-1.21.0) and try to reinstall the extension again

**Comment by rpus** [comment]
Thanks; that explains my issue, as downloads from GitHub are blocked by the web proxy here.

So this is probably a dead end (for me) I'm afraid! Thanks for the help...

**Comment by SLdragon** [comment]
You're welcome!
