### ISSUE TITLE
Dockerfile.arm32v7 - incorrect image causing failure

### ISSUE THREAD

**Issue by kpakur** [microsoft/vscode-azure-iot-edge#543]
- VSCode Version: 1.44.2
- OS Version: Windows 10
- Extension Version: 1.21.0

Steps to Reproduce:

1. Use Command Azure IoT Edge: New IoT Edge Solution (should contain one module named: SampleModule)
2. Generated solution target should be: netcoreapp3.1
3. Change the Default Platform to arm32v7
4. Use command Azure IoT Edge: Build IoT Edge Solution
5. Error: Step 4/12 : RUN dotnet restore ---> Running in f27622ae0751 A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders

The issue is related to the generated Dockerfile.arm32v7. The generated file is 
`FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleModule.dll"]`

**where the expected content of the file (note the difference in the first line) should be:**
`FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleModule.dll"]
`
The module complied with that file on Windows 10 AMD64 has been tested on Raspberry Pi 2 ARM32v7 and works as expected.

See also https://github.com/dotnet/dotnet-docker/issues/1537#issuecomment-615269150
Note that for dotnet 2.1 Dockerfile.arm32v7 are generated fine as expected

**Comment by RotateAt60MPH** [comment]
I can verify this works for PI4, as well, which is a different animal.

**Comment by RotateAt60MPH** [comment]
Note that the corresponding change should also be made to the 'Dockerfile.arm32v7.debug' file as well.

**Comment by blackchoey** [comment]
@kpakur Building an arm32v7 image on amd64 machine may introduce unexpected issues (when the application uses platform specific things), which could spend people a lot of time on troubleshooting. The template uses the `3.1-buster-arm32v7` on purpose to avoid situations that people don't realize they're building arm32v7 images on an amd64 machine.

The dockerfile created by the extension is just an example to help you get started. If you‘re sure that you can build the arm32v7 image on amd64 machine (like the approach shared in another issue you mentioned earlier), you can absolutely modify the dockerfile according to your requirement.

For the template, we will keep using the `3.1-buster-arm32v7` tag for arm32v7 dockerfile. So people can be aware they're building arm32v7 images on non-arm32v7 platform as early as possible. Please let us know if you have further questions on this.

**Comment by RotateAt60MPH** [comment]
@blackchoey So what is the guidance if you are developing on an amd64 machine and wanting to build and push a module that for the rPI (arm32v7)?  Right now the default buster template will not let you continue.  Changing to sdk:31 is the ONLY way to build and push a module to rPI4.    Adding on to that, what do you do if there _are_ platform-specific features you want to use?  Thanks!

**Comment by blackchoey** [comment]
@RotateAt60MPH You can refer following blog post to build the image on a remote Raspberry Pi: https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/ 
In this way, you don't need to modify the dockerfile. There's also no additional actions to take if you uses platform specific features in your application.

**Comment by kpakur** [comment]
Building ARM64v8 also requires modification of the appropriate Dockerfiles in a similar way.

**Comment by kpakur** [comment]
@RotateAt60MPH so when I actually write code that will be use on many different edge devices including ARM32, ARM64 and AMD64 I should have one machine of each just to build the code? What about building the modules using Azure Pipelines for different platforms?

**Comment by blackchoey** [comment]
@kpakur As mentioned earlier, you can build non amd64 images on amd64 machine if you're sure this will work. Otherwise it's better to build on target platform to avoid unexpected issue.

Another important thing to notice: if the base image is available on multiple platforms, docker will pull the **amd64** image when building on amd64 machine. This will also cause problems when you run the result image on arm32v7.

For Azure Pipelines, you can self-host arm32/arm64 build agent to build related images.

**Comment by blackchoey** [comment]
Since there're no further questions, I will close this issue. Feel free to open new issues if you meet other problems.
