### ISSUE TITLE
Cannot show other deployment template file when adding module from command palette 

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#547]
- VSCode Version: any
- OS Version: any
- Extension Version: 1.21.0

Steps to Reproduce:

1. Open existing IoT Edge solution
2. Duplicate the default template.json file and rename to deployment.1.template.json.
3. In command palette, add new module, in the deployment template file dropdown list, cannot see deployment.1.template.json.

Does this issue occur when all other extensions are disabled?: Yes

**Comment by SLdragon** [comment]
From the code history, seems we only support select **/deployment.template.json file, and we need further disscussion about this feature

**Comment by SLdragon** [comment]
We have update the extension to 1.22.0, now it support to select different deployment template json file
