### ISSUE TITLE
Trojan detected in one of the components

### ISSUE THREAD

**Issue by andrepodnozov** [microsoft/vscode-azure-iot-edge#551]
- VSCode Version: 1.45.1
- OS Version: Windows 10 Ent 1909 18363.836
- Extension Version: 1.21.0 or 1.22.0

Steps to Reproduce:

1. Extension update happened
2. Windows Defender detected a threat

Threat: Trojan:Win32/Zpevdo.A
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
file: C:\Users\apodnozov\.vscode\extensions\vsciot-vscode.azure-iot-edge-1.21.0\iotedgehubdev\0.14.0\iotedgehubdev.exe

Potential root cause: https://github.com/Azure/iotedgehubdev/issues/274

<img width="483" alt="IotedgehubdevTrojan" src="https://user-images.githubusercontent.com/10746890/83198530-30d5be00-a0f4-11ea-9933-bece742d3d02.png">

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by SLdragon** [comment]
Hi, @andrepodnozov , we updated our simulator to 0.14.1, now the windows defender false alarm issue has been solved. We are now contacting Windows Defender team for more information about this. You can just reopen vscode or visual studio, then it would download the latest version

**Comment by andrepodnozov** [comment]
I confirm that the updated version doesn't cause the false alarm anymore. Thanks!

**Comment by SLdragon** [comment]
Thanks, now Windows defender team also help us solve the false alarm issue for 0.14.0, thanks for your feedback!
