### ISSUE TITLE
Add non-build files to Azure IoT Edge modules

### ISSUE THREAD

**Issue by sharbt** [microsoft/vscode-azure-iot-edge#566]
Please refer https://github.com/Azure/iotedge/issues/4026 as discussed there.

**Comment by konichi3** [comment]
Hi @sharbt 

can you provide more details? 

- Repro steps or scenarios impacted (if feature request)
- Expected outcome
- Is this blocking issue?

**Comment by sharbt** [comment]
@konichi3 
Please refer https://github.com/Azure/iotedge/issues/4026 as already describe there.
I am not sure if already feature exists , if yes let me know if can be done.
Otherwise , will be needed as there is no way can add non-build files (artifacts/images/readme file) to existing docker service.

**Comment by konichi3** [comment]
@sharbt 

Thank you for opening a new issue with the update. We will investigate and come back.

**Comment by avagraw** [comment]
@sharbt
One of the following approaches should work for you
1. If you are using Visual Studio you can Add the files to the Project and ensure the Copy on Output is set to 'Always'
OR
2. You can modify the Docker File to include those required files

**Comment by konichi3** [comment]
@sharbt 

We are closing the issue. If the issue persists, feel free to re-open or create a new one
