### ISSUE TITLE
.config should be config

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-edge#57]
After `Build IoT Edge solution`, the `.config` should be `config`:
![image](https://user-images.githubusercontent.com/1050213/37507768-2e8f852e-292b-11e8-9da9-2d8acd3714a9.png)

**Comment by czgtest** [comment]
fix work, the .config has changed to config in message

![image](https://user-images.githubusercontent.com/35018765/37693919-ca4f05f4-2cfd-11e8-921f-4db7ed42dd08.png)
