### ISSUE TITLE
Detected as a threat by windows defender

### ISSUE THREAD

**Issue by baywet** [microsoft/vscode-azure-iot-edge#570]
- VSCode Version: 1.54.3
- OS Version: windows 10 20H2 19042.867
- Extension Version: 1.23.0

Steps to Reproduce:

Identical to #551

Does this issue occur when all other extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/7905502/112844708-09cc7d80-9072-11eb-818c-87d82bb94ba3.png)

**Comment by marianan** [comment]
@baywet , we are tracking the issue at https://github.com/Azure/iotedgehubdev/issues/274
