### ISSUE TITLE
Windows Defender report Trojan:Win32/Zpevdo.B !!!

### ISSUE THREAD

**Issue by micli** [microsoft/vscode-azure-iot-edge#573]
- VSCode Version: 1.55.0
- OS Version: 10.0.19042.867
- Extension Version: 1.23.0

When user click "Restart to Update", Windows defender report virus:
file: C:\Users\micl\.vscode\extensions\vsciot-vscode.azure-iot-edge-1.23.0\iotedgehubdev\0.14.6\iotedgehubdev.exe
Steps to Reproduce:
![image](https://user-images.githubusercontent.com/2059006/113251808-7dca8800-92f5-11eb-93a2-05f9a3a8192a.png)

Does this issue occur when all other extensions are disabled?: Yes

**Comment by MagdaPaj** [comment]
the same problem:
![image](https://user-images.githubusercontent.com/25376553/113295039-f7fc0c00-92f7-11eb-98d5-f548a9906095.png)

It may be related to this: https://github.com/Azure/iotedgehubdev/issues/274

**Comment by BogdanGeorge** [comment]
Hello, I have the same problem.I have iotedgehubdev v0.14.6 and VS 2019 with Iot Edge Hub Tools extensions v0.14.6 but i still get the same error from Windows Defender Tojan:Win32/Zpevdo.B. Any suggestions ?

**Comment by smcd253** [comment]
Hi all,

Please follow [these steps](https://github.com/Azure/iotedgehubdev/issues/274#issuecomment-812644362) to resolve the issue.

**Comment by konichi3** [comment]
We are closing the issue. Please file a new issue if the issue still persists
