### ISSUE TITLE
[doc] outputName is wrong

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode-azure-iot-edge#58]
In https://github.com/shizn/azure-docs-pr/blob/master/articles/iot-edge/tutorial-multiple-modules-in-vscode.md#prepare-your-first-iot-edge-solution,
`"PipeFunctionToIoTHub": "FROM /messages/modules/SampleFunction/outputs/output1 INTO $upstream"` shoud be `"PipeFunctionToIoTHub": "FROM /messages/modules/SampleFunction/outputs/alertOutput INTO $upstream"`

**Comment by adashen** [comment]
how about change to FROM /messages/modules/SampleFunction/outputs/* INTO $upstream like the configuration in https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function#run-the-solution.

@formulahendry Where did you find the output name(alertOutput). Is it a special schema in founction? Where is it documented?

**Comment by formulahendry** [comment]
It is from https://github.com/Azure/dotnet-template-azure-iot-edge-function/blob/06bea79af0dfafa29f965588456b90b651d985a5/content/dotnet-template-azure-iot-edge-function/CSharp/EdgeHubTrigger-Csharp/function.json#L12

I am going to change the name to `output1`, it would be more general

**Comment by formulahendry** [comment]
PR is sent: https://github.com/Azure/dotnet-template-azure-iot-edge-function/pull/10

**Comment by adashen** [comment]
Since dotnet template is updated. Close this issue
