### ISSUE TITLE
Change Deprecated Call on Python Module

### ISSUE THREAD

**Issue by asergaz** [microsoft/vscode-azure-iot-edge#592]
- VSCode Version: 1.60.1
- OS Version: Windows 10 Version 21H1
- Extension Version: 1.24.3

When creating IoT Edge **Python** Module we notice that main.py brings a deprecated call to IoTHubModuleClient.

Please change main.py line 28:

From:

`input_message = await module_client.receive_message_on_input("input1")  # blocking call`

to

`input_message = await module_client.on_message_received("input1")  # blocking call`

Related issue: https://github.com/microsoftdocs/azure-docs/issues/81158

**Comment by cindydeng1998** [comment]
Thank you for the detailed report @asergaz, we have added this to our backlog and will report back as soon as we've made the update.
