### ISSUE TITLE
Intell-sense does not work for python code 

### ISSUE THREAD

**Issue by lirenhe** [microsoft/vscode-azure-iot-edge#61]
<img width="511" alt="capture" src="https://user-images.githubusercontent.com/9100546/37510782-45163ee4-2937-11e8-9565-40465bcca9a0.PNG">

Please advise what to do or install to solve that in the document.
The error I got is '[pylint] E0401:Unable to import 'iothub_client''

**Comment by adashen** [comment]
@formulahendry can you help to have a check on this?

**Comment by adashen** [comment]
@formulahendry If we think this is a issue from python. We may raise an issue in their repo and link here.

**Comment by formulahendry** [comment]
The root cause is there is no azure-iothub-device-client sdk installed on user's dev machine. After running `pip install -r requirements.txt` (it will install all pip library on dev machine), the error no longer exists. We may want to mention this as an optional step in the document. @shizn

**Comment by formulahendry** [comment]
Oh, seems running `pip install -r requirements.txt` still does not work..

**Comment by formulahendry** [comment]
Open an issue to Python extension: https://github.com/Microsoft/vscode-python/issues/1151

**Comment by formulahendry** [comment]
Not extension issue, should be issue of pylint: https://github.com/PyCQA/pylint/issues/1955

**Comment by shizn** [comment]
Need to update the doc to instruct user to install python device sdk.

**Comment by blackchoey** [comment]
The python template now uses Python SDK V2. The error will disappear after installs the SDK on dev machine.
