### ISSUE TITLE
Threat detected: Trojan/Generic.ASMalwS.3124987 in iotedgehubdev.exe

### ISSUE THREAD

**Issue by bqstony** [microsoft/vscode-azure-iot-edge#618]
Hi,

This morning, after automatic update in VSCode, the iotedgehubdev.exe was moved to quarante by me cisco endpoint protection.

My IT has ordered a deep scan an the result is not so good.

https://www.virustotal.com/gui/file/804a25f9797a8b5d3b61f6b4152172e6d29c98bed918b91892e766d3ffbb1d26/detection 

![image](https://user-images.githubusercontent.com/10487253/141327880-fbf508dc-68be-49d0-b856-063c2e4c4f1f.png)
![image](https://user-images.githubusercontent.com/10487253/141329025-e194926f-f1fe-4e3e-b59f-0a0516d27d4f.png)

- VSCode Version: 1.62.1
- OS Version: W10 - 21H1
- Extension Version: Azure IoT Edge v1.25.1

**Comment by bqstony** [comment]
Cisco team could unblock it. Meaby it helps others:

Feedback from cisco: 
```
Our analysis shows that the file is indeed benign. We have rectified the issue by changing the file disposition which effectively allows the customer to access the file. ... The source of the conviction has been notified so that they can use this example to improve detection content, which will help prevent future false positives.
```

**Comment by konichi3** [comment]
Thanks for sharing the outcome. We are closing the issue.
