### ISSUE TITLE
Unable to start filter module in Python

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-azure-iot-edge#63]
Follow the doc : https://review.docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?branch=pr-en-us-35471 
Got the following error:

Machine temperature 27.0104326896 exceeds threshold 25
Confirmation[0] received for message with result = OK
    Properties: {'MessageType': 'Alert'}
    Total calls confirmed: 11
    Data: <<<{"machine":{"temperature":27.030986996382,"pressure":1.6870744679422534},"ambient":{"temperature":20.770010575312195,"humidity":24},"timeCreated":"2018-03-16T08:34:29.5137673Z"}>>> & Size=177
    Properties: {}
    Total calls received: 12
Machine temperature 27.0309869964 exceeds threshold 25
Confirmation[0] received for message with result = OK
    Properties: {'MessageType': 'Alert'}
    Total calls confirmed: 12

Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]

IoT Hub Client for Python
Adding TrustedCerts from: /mnt/edgemodule/edge-device-ca.cert.pem
set_option TrustedCerts successful
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit.
Error: Time:Fri Mar 16 08:45:46 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:584 Failure: socket state is not closed.
Error: Time:Fri Mar 16 08:45:46 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:751 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Mar 16 08:45:46 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed opening the underlying I/O.
Error: Time:Fri Mar 16 08:45:46 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Fri Mar 16 08:45:46 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1932 failure connecting to address iverwin10.fareast.corp.microsoft.com.
Error: Time:Fri Mar 16 08:45:48 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:584 Failure: socket state is not closed.
Error: Time:Fri Mar 16 08:45:48 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:751 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Mar 16 08:45:48 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed opening the underlying I/O.
Error: Time:Fri Mar 16 08:45:48 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Fri Mar 16 08:45:48 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1932 failure connecting to address iverwin10.fareast.corp.microsoft.com.
Error: Time:Fri Mar 16 08:45:52 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:584 Failure: socket state is not closed.
Error: Time:Fri Mar 16 08:45:52 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:751 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Mar 16 08:45:52 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed opening the underlying I/O.
Error: Time:Fri Mar 16 08:45:52 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Fri Mar 16 08:45:52 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1932 failure connecting to address iverwin10.fareast.corp.microsoft.com.
Error: Time:Fri Mar 16 08:46:00 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:584 Failure: socket state is not closed.
Error: Time:Fri Mar 16 08:46:00 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:751 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Mar 16 08:46:00 2018 File:/usr/sdk/src/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1251 Failed opening the underlying I/O.
Error: Time:Fri Mar 16 08:46:00 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed

**Comment by adashen** [comment]
Seems the same issue as #47 . The reason is Edge start filter module before edgehub. The connection will be successful after several retry.

**Comment by formulahendry** [comment]
Duplicated with #47
