### ISSUE TITLE
Edge Simulator exits after starting simulation

### ISSUE THREAD

**Issue by Vic152** [microsoft/vscode-azure-iot-edge#641]
- VSCode Version:
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
- OS Version: Win 10
- Extension Version: v1.25.9

Steps to Reproduce:
1. Setup IoT Edge Simulator
2. Run deployment template in simulator

Observed:
1. Containers start in Docker
2. However in the VS Code terminal I see the following and it exits

ERROR: Windows named pipe error: The pipe has been ended. (code: 109)
ERROR: Error while executing command: docker-compose -f C:\Users\xxx\AppData\Local\.iotedgehubdev\data\data\docker-compose.yml up. Command '['docker-compose', '-f', 'C:\\Users\\xxx\\AppData\\Local\\.iotedgehubdev\\data\\data\\docker-compose.yml', 'up']' returned non-zero exit status 1.

I tried to delete `docker-compose.yml` and starting the simulator again - did not help. I also use Visual Studio on the same machine with simulator. They share `docker-compose.yml`?

Does this issue occur when all other extensions are disabled?: Yes/No N/A extension is used.

**Comment by konichi3** [comment]
VSCode and VS do not share the same docker compose file. Any chance the docker-compose.yaml file is corrupted? Is this still blocking you?

**Comment by Vic152** [comment]
To be honest it does not matter since you are spinning down this project. I will try to move away from Microsoft as your solutions are not suitable for production environments.
