### ISSUE TITLE
IOT hub visual studio code not seeing opcpublisher messages sent 

### ISSUE THREAD

**Issue by javierdve** [microsoft/vscode-azure-iot-edge#643]
- VSCode Version:1.71.2
- OS Version:Windows NT x64 10.0.1904 (windows 10)
- Extension Version:Azure IoT Tools v0.3.0

Steps to Reproduce:

I am trying to see the messages with Visual Code and the IOT extension and also with IOT Explorer. In the past it worked fine but now I am unable to see any json message. The fact is that IOT hub seems to be sending the messages because I created an storage account and a route (message routing) to that storage account. I am seeing the data is being stored.

For monitoring with VCode I added a different consumer groups in the built-in endpoint of azure iot hub and then I select in visual studio extension settings that consumer group. But when I press monitor Star monitoring built-in event endpoint the output of Visual code shows only this and nothing else:
[IoTHubMonitor] Start monitoring message arrived in built-in endpoint for device [deviceopcgatewaytest] ...
[IoTHubMonitor] Created partition receiver [0] for consumerGroup [visualcodemonitoring]
[IoTHubMonitor] Created partition receiver [1] for consumerGroup [visualcodemonitoring]
[IoTHubMonitor] Created partition receiver [2] for consumerGroup [visualcodemonitoring]
[IoTHubMonitor] Created partition receiver [3] for consumerGroup [visualcodemonitoring]

I have searched several forums trying different options without success. Any clue about how to proceed or what could I try or read. As I have used Visual Code and also IOT explorer and I am not seeing messages maybe it is something I am forgetting but as I wrote consumer group is in place and I don't know what more to do by now.

Does this issue occur when all other extensions are disabled?: It also happens with IOT Explorer.

Thanks a lot and best regards,

**Comment by konichi3** [comment]
@javierdve Can you open the issue [there](https://github.com/microsoft/vscode-azure-iot-toolkit) instead as it also repros with IoT Explorer and IoT Hub toolkit?
