### ISSUE TITLE
The router name in "routers" block should leverage module name

### ISSUE THREAD

**Issue by adashen** [Microsoft/vscode-azure-iot-edge#66]
1. New edge solution in vscode
2. input "test" as module name.
3. Open deployment.template.json and the router name in routers are "sensorToFilter" "filterToIoTHub". It is confusing to user the router name doesn't honor the module name

**Comment by czgtest** [comment]
Now the router name in routers are "sensorTotest" "testToIoTHub", please see screenshot as bellow.

![image](https://user-images.githubusercontent.com/35018765/37692014-f6cb1224-2cf0-11e8-8c89-0e4835d6b209.png)
