### ISSUE TITLE
Replace `iotedgehubdev` with the new `iotedgedev`

### ISSUE THREAD

**Issue by paule96** [microsoft/vscode-azure-iot-edge#660]
It would be nice if this extension would use the tool `iotedgedev` that is still maintained and supported. It also adds lot features, like docker in docker support, so we could use the simulator als inside of devcontainers.

https://github.com/Azure/iotedgedev

**Comment by konichi3** [comment]
Thanks for the feedback.

Unfortunately, VS Extension is in maintenance mode and you are welcomed to use `iotedgedev` directly as described in the doc.
