### ISSUE TITLE
[Doc] Inform users that the Python module image build step might take several minutes for the first time.

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode-azure-iot-edge#68]
From https://github.com/MicrosoftDocs/azure-docs-pr/pull/35471#commitcomment-28118909

**Comment by adashen** [comment]
fixed in https://review.docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?branch=pr-en-us-35471#create-a-docker-image-and-publish-it-to-your-registry
