### ISSUE TITLE
[Doc] Should not use the "latest" tag during deployment

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode-azure-iot-edge#69]
From https://github.com/MicrosoftDocs/azure-docs-pr/pull/35471#commitcomment-28119491

If the user used the new Edge extension to build and push the image, the image tag should be the version and the platform, e.g., "0.0.1-arm64", not "latest".

**Comment by adashen** [comment]
fixed in https://review.docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?branch=pr-en-us-35471#run-the-solution
