### ISSUE TITLE
[New IoT Edge solution] if input module name is  /Sample/Module/, will get error

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#74]
if input module name is  /Sample/Module/, will get error : 
Command failed with exit code 214750003

**Comment by czgtest** [comment]
another issue 

if input module name is  Edge:Solution,  will get error too.

![image](https://user-images.githubusercontent.com/35018765/37644049-74c72e0e-2c5d-11e8-8ad2-fb2b1f7f2c5f.png)

**Comment by adashen** [comment]
@czgtest please verify the fix

**Comment by czgtest** [comment]
fix work now,  if input module name is /Sample/Module/  or Edge:Solution,  it will reminder user to input alphanumeric characters

![image](https://user-images.githubusercontent.com/35018765/37747416-1489037e-2dba-11e8-9d9a-2ddca17a85c8.png)


![image](https://user-images.githubusercontent.com/35018765/37747520-9769d228-2dba-11e8-9905-2414faee9f8d.png)
