### ISSUE TITLE
[New IoT Edge solution]Do we allow Solution /Module Name to be  spaces ?

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#75]
![image](https://user-images.githubusercontent.com/35018765/37643833-c6472834-2c5c-11e8-80ca-c360e734c2d0.png)

**Comment by adashen** [comment]
@LazarusX it seems similar to another naming issue. So also assigned to you.

**Comment by adashen** [comment]
@czgtest please verify

**Comment by czgtest** [comment]
now if enter space key to solution/Module name,  it doesn't allow now.

![image](https://user-images.githubusercontent.com/35018765/37747627-212296da-2dbb-11e8-9b7b-5c453c8c14c1.png)
