### ISSUE TITLE
[Add IoT Edge Module] if the module name contains double quotes,will get error.

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#76]
if the module name is "c#module03", and  localhost:5000/"c#module03"

![image](https://user-images.githubusercontent.com/35018765/37644636-675ae092-2c5f-11e8-820c-4d718ee99bb4.png)

![image](https://user-images.githubusercontent.com/35018765/37644749-bc573f78-2c5f-11e8-8b12-aecac7d1fb5f.png)

![image](https://user-images.githubusercontent.com/35018765/37644574-3455beb0-2c5f-11e8-9bb5-a310e3ff7fb5.png)

Verify the deployment.template.json file is not updated: the module JSON is not added into the modules section

**Comment by adashen** [comment]
@LazarusX  please have a look. Actually this is a user error to input invalid name. But we may find a better way to report the issue to user.

**Comment by formulahendry** [comment]
For #74, #75, #76,  I suggest check the name when user type in the input box and only allow alphanumeric characters or the symbol _

**Comment by adashen** [comment]
@czgtest Please help to verify the fix

**Comment by czgtest** [comment]
Now solution/module name only allow alphanumeric characters .
![image](https://user-images.githubusercontent.com/35018765/37747842-1155aef8-2dbc-11e8-8d4a-b6adf5e0440e.png)
