### ISSUE TITLE
[Debug Edge Module] Can't debug module.

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#78]
steps:
1.create a new IoT Edge solution (c# Module)
2.add 3 IoT Edge Module
3.Build IoT Edge Solution 
4.Deploy Edge Device 
5.Setup and start Edge runtime 
6.Debug Edge Module 
   Navigate to debug view, and select “Debug IoT Edge Module SampleModule (.NET Core)”, then press F5 
get error : 
Executing: docker exec -i SampleModule sh -c "sh -s" < C:\Users\v-czg\.vscode\extensions\ms-vscode.csharp-1.14.0\scripts\remoteProcessPickerScript
Linux
stderr: sh: 1: ps: not found
Error Message: Command failed: docker exec -i SampleModule sh -c "sh -s" < C:\Users\v-czg\.vscode\extensions\ms-vscode.csharp-1.14.0\scripts\remoteProcessPickerScript
sh: 1: ps: not found

![image](https://user-images.githubusercontent.com/35018765/37647896-6e89e2b0-2c68-11e8-8dbd-47f17b55879f.png)

**Comment by adashen** [comment]
To debug the CSharp module, we need to use the debug image in deployment.template.json of the module. Can you check the image used in the template and try again?

**Comment by czgtest** [comment]
@adashen ,  after I use the debug image in deployment.template.json and push debug image to container,  I can debug now, but it unable to open 'Program.cs': File not found (file:///c:/chen/EdgeTool/0320/EdgeSolution/Program.cs).

Actually,  the file path is C:\chen\EdgeTool\0320\EdgeSolution\modules\SampleModule\Program.cs

Now How to debug the SampleModule ?

![image](https://user-images.githubusercontent.com/35018765/37691732-d70706b6-2cee-11e8-8130-2eb1ee9c7ff5.png)

![image](https://user-images.githubusercontent.com/35018765/37691568-dbb9ec42-2ced-11e8-8bb0-124c0d9d9320.png)

**Comment by formulahendry** [comment]
Please make sure you are using the correct launch.json generated by `New IoT Edge solution` or `Add IoT Edge Module`

**Comment by czgtest** [comment]
fix work now, the source File Map path should be configured correctly in Launch.json 

![image](https://user-images.githubusercontent.com/35018765/37692785-e9fec432-2cf5-11e8-8ab9-3d606dc877bf.png)
