### ISSUE TITLE
[Convert C# Module]display a message instead of an error

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#81]
steps:
1.Open a legacy C# Module project 
2. Right-click on .csproj file, and click Convert to IoT Edge Module 
Verify an error will throw out.
It would be better to display a message instead of an error.
![image](https://user-images.githubusercontent.com/35018765/37690921-2d2b3edc-2ce9-11e8-97fc-c825f1f8d181.png)

**Comment by czgtest** [comment]
another scenario 
1. open new vscode window without any project
2. press F1 and select Edge:Add IoT Edge Module.
it will display error message 
![image](https://user-images.githubusercontent.com/35018765/37695507-e4dea232-2d0a-11e8-9cbf-4e35e6f1bdb2.png)
we want to display an information message
![image](https://user-images.githubusercontent.com/35018765/37695555-3619d8e2-2d0b-11e8-9c67-556b51afd66a.png)

**Comment by shizn** [comment]
by design
