### ISSUE TITLE
[Convert C# Module] do we need to support command "Convert to IoT Edge Module"

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#82]
now user can click host.json file to select "Convert to IoT Edge Module", but the edge command is not support "Convert to IoT Edge Module" now.

1.Open a legacy C# Function Module project 
2.Right-click on host.json file, and click Convert to IoT Edge Module

**Comment by formulahendry** [comment]
Do you mean trigger "Convert to IoT Edge Module from Command Palette?
I think we do not plan to support since this is a temporary command.
cc @adashen

**Comment by czgtest** [comment]
if don't plan to support it, we can close this issue.

**Comment by adashen** [comment]
close as designed
