### ISSUE TITLE
[Add IoT Edge Module ]the second module route JSON is not added into the routes block

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#83]
Steps:
1.create a new IoT edge solution
2.add 2 function modules
3.Verify the deployment.template.json file
the second module route JSON is not added into the routes block.
now it only has the first module route json here.

![image](https://user-images.githubusercontent.com/35018765/37692408-4c0ead02-2cf3-11e8-9e95-ac27e1a8cc73.png)

**Comment by formulahendry** [comment]
We would not update the routes when add a new module, since user would already do some changes on the routes, and we could not assume the data flow of the module.
