### ISSUE TITLE
[Add IoT Edge Module]update the launch.json file failed.

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#84]
steps:
1.create new IoT Edge solution
2.Add 1 C# Edge Module
3.delete the launch.json in your .vscode folder 
4.press F5 and select IoT Edge (.NER Core).  
   verify launch.json is generated.
5. Add another C# Edge Module 
  verify the module was created successfully, but get an error when updated launch.json file. the new module was not added in launch.json.

![image](https://user-images.githubusercontent.com/35018765/37693324-da68fdae-2cf9-11e8-8451-2df33e114283.png)

![image](https://user-images.githubusercontent.com/35018765/37693456-b41f06b0-2cfa-11e8-9a8f-2197b8ff8aea.png)

**Comment by adashen** [comment]
@czgtest please help to verify the fix

**Comment by czgtest** [comment]
verify pass , the launch.json file can be update successfully now.
![image](https://user-images.githubusercontent.com/35018765/37747979-c1dfa4d6-2dbc-11e8-918e-6a0b8d406c6c.png)
