### ISSUE TITLE
[Create Edge Device] Create edge device failure when named edgeDeviceC# 

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#85]
Steps:
1.press F1 and select Edge:create Edge Device
2.input device ID named edgeDeviceC# 
  verify there is an error as bellow.

[Edge Device] Creating Edge Device 'edgeDeviceC#'
[Edge Device] [Create] error: ArgumentError: Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>

![image](https://user-images.githubusercontent.com/35018765/37697504-28a7f2e0-2d18-11e8-84d1-3b18cd07fc06.png)

**Comment by formulahendry** [comment]
This is issue in IoT Toolkit extension

**Comment by formulahendry** [comment]
Fixed in IoT Toolkit: https://github.com/Microsoft/vscode-azure-iot-toolkit/issues/89
