### ISSUE TITLE
'Debug IoT Edge Module (.NET Core)' fails with 'Name not defined in current configuration.'

### ISSUE THREAD

**Issue by jessebenson** [Microsoft/vscode-azure-iot-edge#94]
Create a new IoT Edge Solution named EdgeSolution with a C# Module SampleModule.
Build IoT Edge Solution
Deploy to IoT Edge device (local machine)
Debug > Debug IoT Edge Module SampleModule (.NET Core)

Observe:  'Name not defined in current configuration' error in VS Code.

**Comment by adashen** [comment]
@jessebenson , to debug the c# module, we need to use amd64.debug image, So have you specify the debug version of the image in your deployment.template.json file?

**Comment by jessebenson** [comment]
Yes, I am using the amd64.debug image.  I left off that step above, but I am hitting the same error when I try to debug: 

![image](https://user-images.githubusercontent.com/8907830/38055569-f1fea0a0-328e-11e8-8839-a7994258a2cf.png)

**Comment by adashen** [comment]
@jessebenson I cannot reproduce the issue on my side. Can you check the version of you C# extension and also the VSCode version? And is The edge solution currently is open as root folder in your workspace?

**Comment by jessebenson** [comment]
Windows 10
Visual Studio Code:  1.21.1
Shell: 1.7.9
Azure IoT Edge extension:  0.2.0

Yes - creating New IoT Edge Solution opens only that window, and reopening the solution folder in VS Code hits the same issue.

**Comment by adashen** [comment]
a known issue caused by "VS Live Share" V0.2.260. Need to uninstall the extension to solve the issue. Close here.
