### ISSUE TITLE
Add support for custom Docker arguments in module.json

### ISSUE THREAD

**Issue by jessebenson** [Microsoft/vscode-azure-iot-edge#95]
**ISSUE**
Some Dockerfiles require additional arguments to build correctly.  For example, some may require Environment variables or other arbitrary Docker arguments (--add-host).  Right now, the `docker build` command only supports custom image tags:
https://github.com/Microsoft/vscode-azure-iot-edge/blob/master/src/container/containerManager.ts

**SOLUTION**
Add support in module.json for extra Docker build commands.  E.g. add a parameter for docker build arguments:

"docker": {
  "build-args": [ "arg1", "arg2" ]
}

**Comment by adashen** [comment]
@jessebenson good suggestion! We will try to figure out how to integrate the custom build arguments in to module.json.
