### ISSUE TITLE
docker push image failed due to not start a local registry

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#96]
Right-click the deployment.template.json file, and click Build IoT Edge Solution
verify all the modules are built ,but pushed failed
![image](https://user-images.githubusercontent.com/35018765/38004787-6762b134-3270-11e8-9f4e-1c0f69eba277.png)

because user not start a local registry:   docker run -d -p 5000:5000 --name registry registry:2  

but in our tool , Did not tell the user to register it.

**Comment by formulahendry** [comment]
User will choose what register to push image (config in module.json). They could choose local registry, Docker Hub, ACR, or other registry, and take care of the steps to set up the registry.
