### ISSUE TITLE
debug Python Module failed

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-azure-iot-edge#98]
1. New IoT Edge solution
2. Add Python Module
3. build and push the Iot edge image
4.Generate IoT Edge Deployment Manifest 
![image](https://user-images.githubusercontent.com/35018765/38016980-56d3e60c-32a3-11e8-9556-377704ecd219.png)
5. Create deployment for Edge device
6.Setup and start Edge runtime 
7.Debug Edge Module 
there is an error: 
Unable to open 'DotNetFunctionInvoker.cs': File not found (file:///home/ahmed/repos/azure-webjobs-sdk-script/src/WebJobs.Script/Description/DotNet/DotNetFunctionInvoker.cs).

![image](https://user-images.githubusercontent.com/35018765/38017098-a344b3d6-32a3-11e8-981b-c52a8bfa7059.png)

**Comment by formulahendry** [comment]
debugging Python Module is not supported yet. So there would be no debug config generated in launch.json. You are not able to debug Python for now.
